src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</description>
    <inlineHelpText>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</inlineHelpText>
    <label>Enable Profile Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</description>
    <inlineHelpText>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</inlineHelpText>
    <label>Enable Profile Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_ID__c</fullName>
    <description>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</description>
    <inlineHelpText>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</inlineHelpText>
    <label>B2C Customer ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</description>
    <inlineHelpText>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</inlineHelpText>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/person-accounts/main/default/classes/B2CIACustomerResolutionPA_Test.cls
/**
 * @author Eric Schultz
 * @date April 21th, 2021
 *
 * @description
 * Tests included
 *      Matches by customerid
 *      Matches customerno and customerlist
 *      Does not match 2 contacts spanning different customerlists
 *      Matches just last name and email
 *      Does not match contact with different last name
 *      Matches email, last name, customer list id
 *      Does not match different customer ids
*/

@IsTest
private class B2CIACustomerResolutionPA_Test {

    @TestSetup static void setup() {
        B2C_CustomerList__c customerList = (B2C_CustomerList__c)TestDataFactory.createSObject('B2C_CustomerList__c', new Map<String,Object>{
            'Name' => 'customerList',
            'Is_Active__c' => true,
            'API_Url__c' => 'https://www.salesforce.com',
            'B2C_Instance__r.Is_Active__c' => true,
            'B2C_Instance__r.API_Url__c' => 'https://www.salesforce.com',
            'Enable_Profile_Publishing__c' => true,
            'Enable_Profile_Creation__c' => true
        });
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with a last name, email, customer id
     * When
     *      We resolve with a customer with a different last name, email, but same customer id
     * Then
     *      We will be returned the existing person account
     */
    /* */
    @IsTest
    static void resolvesCustomerId() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'differntemail@email.com',
            'LastName' => 'DifferentLastName',
            'B2C_Customer_ID__pc' => 'customerid',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_Customer_ID__c = 'customerid'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList[0].Id,
            [SELECT Id FROM Contact WHERE AccountId = :account.Id LIMIT 1].Id
        );
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with a last name, email, customer id, customer list id
     * When
     *      We resolve with a customer with a different last name, email, but same customer no and customer list id
     * Then
     *      We will be returned the existing person account
     */
    /* */
    @IsTest
    static void resolvesCustomerNoAndCustomerList() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'differntemail@email.com',
            'LastName' => 'DifferentLastName',
            'B2C_Customer_No__pc' => 'customerNo',
            'B2C_CustomerList_ID__pc' => 'customerList',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_Customer_No__c = 'customerNo',
            B2C_CustomerList_ID__c = 'customerList'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );


            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList[0].Id,
            [SELECT Id FROM Contact WHERE AccountId = :account.Id LIMIT 1].Id
        );
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with a last name, customer list id and email
     * When
     *      We resolve with a customer with same list name and email and a customer list
     * Then
     *      We will be returned the existing person account
     */
    /* */
    @IsTest
    static void resolvesContactWithCustomerListIdLastNameAndEmail() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'email@email.com',
            'LastName' => 'LastName',
            'B2C_CustomerList_ID__pc' => 'CustomerList',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_CustomerList_ID__c = 'CustomerList'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList[0].Id,
            [SELECT Id FROM Contact WHERE AccountId = :account.Id LIMIT 1].Id
        );
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with customer id
     * When
     *      We resolve with a customer with different customer id, same email, last name
     * Then
     *      We will be returned the existing person account
     */
    /* */
    @IsTest
    static void doesNotResolveDifferentCustomerIds() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'email@email.com',
            'LastName' => 'LastName',
            'B2C_Customer_ID__pc' => 'CustomerId',
            'B2C_CustomerList_ID__pc' => 'customerList',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_CustomerList_ID__c = 'customerList',
            B2C_Customer_ID__c = 'CustomerId2'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList,
            null
        );
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      2 different customer lists and one person account existing for customer list 1
     * When
     *      We resolve with a customer with same last name and email with a different customer list
     * Then
     *      We will be returned a new contact
     */
    /* */
    @IsTest
    static void createTwoContactsSpanningDifferentCustomerListIds() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'email@email.com',
            'LastName' => 'LastName',
            'B2C_CustomerList_ID__pc' => 'customerList',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_CustomerList_ID__c = 'CustomerList2'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList,
            null
        );
    }

    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with a last name and email
     * When
     *      We resolve with a customer with same list name and email and a customer list
     * Then
     *      We will be returned the existing person account
     */
    /* */
    @IsTest
    static void resolvesContactWithLastNameAndEmail() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'email@email.com',
            'LastName' => 'LastName',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_CustomerList_ID__c = 'CustomerList'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList[0].Id,
            [SELECT Id FROM Contact WHERE AccountId = :account.Id LIMIT 1].Id
        );
    }


    /**
     * @see B2CIACustomerResolution.resolve
     * @description
     * Given
     *      Existing person account with a last name and email
     * When
     *      We resolve with a customer with same list, email but different last name
     * Then
     *      We will be returned a new contact
     */
    /* */
    @IsTest
    static void doesNotResolveContactWithDifferentLastName() {

        Account account = (Account)TestDataFactory.createSObject('Account', new Map<String,Object>{
            'PersonEmail' => 'email@email.com',
            'LastName' => 'DifferentLastName',
            'B2C_CustomerList_ID__pc' => 'CustomerList',
            'RecordTypeId' => [SELECT Id FROM RecordType WHERE DeveloperName = 'PersonAccount' LIMIT 1].Id
        });

        Contact c1 = new Contact(
            Email = 'email@email.com',
            LastName = 'LastName',
            B2C_CustomerList_ID__c = 'CustomerList'
        );

        List<List<Contact>> contactResolvedList = new List<List<Contact>>();
        List<Contact> contactFilteredList = new List<Contact>();

        Test.startTest();

            contactResolvedList = B2CIACustomerResolution.resolve(
                new List<Contact>{ c1 }
            );

            Map<String, Object> contactFilterMap = new Map<String, Object>();

            contactFilterMap.put(
                'Contact',
                c1
            );

            contactFilterMap.put(
                'ContactMatches',
                contactResolvedList[0]
            );

            Flow.Interview.B2C_Commerce_Contact_Filter_Matches contactFilterMatchFlow = new Flow.Interview.B2C_Commerce_Contact_Filter_Matches(contactFilterMap);
            contactFilterMatchFlow.start();

            contactFilteredList = (List<Contact>)(contactFilterMatchFlow.getVariableValue('ContactMatchesResult'));

        Test.stopTest();

        System.assertEquals(
            contactFilteredList,
            null
        );
    }

}