src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Total_Sites__c.field-meta.xml
<CustomField>
    <fullName>Total_Sites__c</fullName>
    <description>... describes the total number of sites configured for this B2C Commerce CustomerList.</description>
    <inlineHelpText>... describes the total number of sites configured for this B2C Commerce CustomerList.</inlineHelpText>
    <label>Total Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Total_CustomerLists__c.field-meta.xml
<CustomField>
    <fullName>Total_CustomerLists__c</fullName>
    <description>... represents the total number of B2C Commerce CustomerLists for his B2C Instance.</description>
    <inlineHelpText>... represents the total number of B2C Commerce CustomerLists for his B2C Instance.</inlineHelpText>
    <label>Total CustomerLists</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/fields/Total_Sites__c.field-meta.xml
<CustomField>
    <fullName>Total_Sites__c</fullName>
    <description>... represents the total number of Sites associated to a given B2C Commerce Instance.</description>
    <inlineHelpText>... represents the total number of Sites associated to a given B2C Commerce Instance.</inlineHelpText>
    <label>Total Sites</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/B2C_Site__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce storefronts.</description>
    <label>B2C Site</label>
    <nameField>
        <label>B2C Site ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/B2C_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance_Id__c</fullName>
    <description>... represents the recordId for the parent B2C Instance.</description>
    <formula>CASESAFEID(Customer_List__r.B2C_Instance__r.Id)</formula>
    <inlineHelpText>... represents the recordId for the parent B2C Instance.</inlineHelpText>
    <label>B2C Instance Id</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Customer_List__c.field-meta.xml
<CustomField>
    <fullName>Customer_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>... represents the B2C Commerce parent CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce parent CustomerList.</inlineHelpText>
    <label>Customer List</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>B2C Sites</relationshipLabel>
    <relationshipName>B2C_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CUpdateCountsHelper.cls
/**
 * @author Abraham David Lloyd
 * @date May 22nd, 2021
 *
 * @description This helper class is used to automate the calculation of siteCounts for CustomerLists and
 * B2C Instances.  When a Site changes, re-calculate the site counts for the parentObjects.
 */
public with sharing class B2CUpdateCountsHelper {



    public static void updateCounts(List<B2C_CustomerList__c> deletedCustomerLists) {

        // Initialize local variables
        Set<String> b2cInstanceIds;
        List<B2C_Instance__c> b2cInstances;

        // Initialize the id-collections
        b2cInstanceIds = new Set<String>();

        // Loop over the collection of deleted customerLists
        for (B2C_CustomerList__c thisCustomerList : deletedCustomerLists) {

            // Build out the identifier collections
            b2cInstanceIds.add(thisCustomerList.B2C_Instance__c);

        }

        // Retrieve the collection of impacted B2C and CustomerList instances
        b2cInstances = [SELECT Id, Total_CustomerLists__c, Total_Sites__c FROM B2C_Instance__c WHERE Id IN :b2cInstanceIds];

        // Loop over the instance-collection and reset the count values
        for (B2C_Instance__c thisInstance : b2cInstances) {
            thisInstance.Total_Sites__c = null;
            thisInstance.Total_CustomerLists__c = null;
        }

        // Only perform the update if records were retrieved
        if (b2cInstances.size() > 0) { Database.update(b2cInstances); }

    }

    public static void updateCounts(List<B2C_Site__c> deletedSites) {

        // Initialize local variables
        Set<String> b2cInstanceIds;
        Set<String> b2cCustomerListIds;
        List<B2C_Instance__c> b2cInstances;
        List<B2C_CustomerList__c> b2cCustomerLists;

        // Initialize the id-collections
        b2cInstanceIds = new Set<String>();
        b2cCustomerListIds = new Set<String>();

        // Loop over the collection of deleted sites
        for (B2C_Site__c thisSite : deletedSites) {

            // Build out the identifier collections
            b2cInstanceIds.add(thisSite.B2C_Instance_Id__c);
            b2cCustomerListIds.add(thisSite.Customer_List__c);

        }

        // Retrieve the collection of impacted B2C and CustomerList instances
        b2cInstances = [SELECT Id, Total_CustomerLists__c, Total_Sites__c FROM B2C_Instance__c WHERE Id IN :b2cInstanceIds];
        b2cCustomerLists = [SELECT Id, Total_Sites__c FROM B2C_CustomerList__c WHERE Id IN :b2cCustomerListIds];

        // Loop over the instance-collection and reset the count values
        for (B2C_Instance__c thisInstance : b2cInstances) {
            thisInstance.Total_Sites__c = null;
            thisInstance.Total_CustomerLists__c = null;
        }

        // Loop over the instance-collection and reset the count values
        for (B2C_CustomerList__c thisCustomerList : b2cCustomerLists) {
            thisCustomerList.Total_Sites__c = null;
        }

        // Only perform the update if records were retrieved
        if (b2cInstances.size() > 0) { Database.update(b2cInstances); }
        if (b2cCustomerLists.size() > 0) { Database.update(b2cCustomerLists); }

    }

}