src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CCustomerListManager_Test.cls
/**
 * @author Abraham David Lloyd
 * @date May 22th, 2020
 *
 * @description This is a test class that validates B2C Customer List data can be retrieve
 * via custom meta-data.  The class validates that retrieval works -- as well as that
 * errors are thrown if no records are found.
 */
@IsTest
private class B2CCustomerListManager_Test {

    // Initialize constants used to drive / inform testing
    private static String metaDataMissingRecordExceptionName = B2CConstant.Errors_ExceptionName_DataRecordMissing;

    // Default the Ids used to identify customerLists
    private static String activeCustomerListId = 'RefArch_Active';
    private static String inActiveCustomerListId = 'RefArch_InActive';

    /**
     * @see B2CCustomerListManager.getCustomerList
     * @description This method validates that we're able to successfully retrieve the details
     * of a customer list -- using the B2C Commerce Customer List ID to retrieve it.
     */
    @IsTest
    static void testRetrieveActiveCustomerListByCustomerListId() {

        // Initialize local variables
        B2C_CustomerList__c testCustomerList;
        B2C_CustomerList__c activeCustomerList;

        Test.startTest();
        
        // Create test-data to seed an active B2C Commerce CustomerList
        activeCustomerList = (B2C_CustomerList__c)TestDataFactory.createSObject('B2C_CustomerList__c', new Map<String,Object>{
            'Name' => activeCustomerListId,
            'Is_Active__c' => true,
            'API_Url__c' => 'https://www.salesforce.com',
            'B2C_Instance__r.API_Url__c' => 'https://www.salesforce.com'
        });

        // Attempt to retrieve the customerList via the customerListManager
        testCustomerList = B2CCustomerListManager.getCustomerList(activeCustomerList.Name);

        Test.stopTest();

        // Validate that the storefront was successfully retrieved by the getStorefront() method
        System.assert(testCustomerList != null, '-->  No active customerList was found; expected an active storefront mapped to customerListId [' + activeCustomerList.Id + '].');

    }


    /**
     * @see B2CCustomerListManager.getCustomerList
     * @description This method validates that we throw an error when we attempt to
     * retrieve the details of an inactive customerList -- using the B2C Commerce
     * customerListId to retrieve it.
     */
    @IsTest
    static void testRetrieveInActiveCustomerListByCustomerListId() {

        // Initialize local variables
        B2C_CustomerList__c testCustomerList;
        B2C_CustomerList__c inActiveCustomerList;
        String exceptionName;
        Boolean testResult;

        // Default the test result
        testResult = false;

        try {

            Test.startTest();

            // Create test-data to seed an inActive B2C Commerce CustomerList
            inActiveCustomerList = (B2C_CustomerList__c)TestDataFactory.createSObject('B2C_CustomerList__c', new Map<String,Object>{
                'Name' => inActiveCustomerListId,
                'Is_Active__c' => false,
                'API_Url__c' => 'https://www.salesforce.com',
                'B2C_Instance__r.API_Url__c' => 'https://www.salesforce.com'
            });

            // Retrieve the details of a customerList that is in-active (should throw an error)
            testCustomerList = B2CCustomerListManager.getCustomerList(inActiveCustomerList.Name);

            Test.stopTest();

        } catch (B2CMetaDataRecordMissingException e) {

            // Pull the name / type of the exception
            exceptionName = e.getTypeName();

            // Validate that the exception type
            if (exceptionName == metaDataMissingRecordExceptionName) { testResult = true; }

        }

        // Validate that the right exception was caught by the in-active record look-up
        System.assert(testResult, '--> Wrong Exception Thrown; Expected [' + metaDataMissingRecordExceptionName + '] and Caught [' + exceptionName + ']');

    }

}