src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Audit_OCAPI_API_Response__c.field-meta.xml
<CustomField>
    <fullName>Audit_OCAPI_API_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether the B2C Commerce OCAPI Interactions should be audited.</description>
    <inlineHelpText>... describes whether the B2C Commerce OCAPI Interactions should be audited.</inlineHelpText>
    <label>Audit B2C Commerce OCAPI Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Base_API_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_API_Url__c</fullName>
    <description>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</description>
    <formula>LEFT(API_Url__c, FIND( &apos;/s/&apos;, API_Url__c)-1)</formula>
    <inlineHelpText>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</inlineHelpText>
    <label>Base API Url</label>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Default_Storefront__c.field-meta.xml
<CustomField>
    <fullName>Default_Storefront__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the default storefront to engage for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the default storefront to engage for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Default Storefront</label>
    <referenceTo>B2C_Site__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</description>
    <inlineHelpText>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</inlineHelpText>
    <label>Enable Profile Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</description>
    <inlineHelpText>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</inlineHelpText>
    <label>Enable Profile Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Retrieval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Customer Profiles can be retrieved from B2C Commerce.</description>
    <inlineHelpText>... describes if Customer Profiles can be retrieved from B2C Commerce.</inlineHelpText>
    <label>Enable Profile Retrieval</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Updates__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</description>
    <inlineHelpText>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</inlineHelpText>
    <label>Enable Profile Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Named_Credential_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Developer_Name__c</fullName>
    <description>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this customerList.</description>
    <inlineHelpText>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this customerList.</inlineHelpText>
    <label>Named Credential Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Named_Credential_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Developer_Name__c</fullName>
    <description>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this B2C Commerce Instance.</description>
    <inlineHelpText>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this B2C Commerce Instance.</inlineHelpText>
    <label>Named Credential Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CCustomerListManager.cls
/**
 * @author Abraham David Lloyd
 * @date January 21st, 2020
 *
 * @description This class is used to retrieve B2C Commerce customer list data and details
 * from custom object definitions.  Each customer-list should also have an associated
 * default storefront.
 */
public with sharing class B2CCustomerListManager extends B2CBaseMeta {

    /**
     * @description Attempts to retrieve a customer list configured via custom objects.  This method
     * automatically throws an error if no records are found.
     *
     * @param customerListId {String} Describes the customerList identifier used to retrieve a given definition
     * @return B2C Returns an instance of the customer list
     */
    public static B2C_CustomerList__c getCustomerList(String customerListId) {
        return getCustomerList(customerListId, true, false);
    }

    /**
     * @description Attempts to retrieve a customer list configured via custom objects.
     *
     * @param customerListId {String} Describes the B2C customerList identifier used to retrieve a given definition
     * @param filterOnActive {Boolean} Describes if the query should filter on active objects only
     * @param returnEmptyObject {Boolean} Describes if an empty sObject should be returned if no results are found
     * @return B2C Returns an instance of the customer list
     */
    public static B2C_CustomerList__c getCustomerList(String customerListId, Boolean filterOnActive, Boolean returnEmptyObject) {

        // Initialize local variables
        List<B2C_CustomerList__c> customerLists;
        String errorMsg;
        Query customerListQuery;
        B2C_CustomerList__c output;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_CustomerListNotFound, customerListId);

        // Seed the default query structure to leverage
        customerListQuery = getDefaultQuery();

        // Define the record limit for the query
        customerListQuery.setLimit(1);

        // Define the default where-clause for the query
        customerListQuery.addConditionEq('Name', customerListId);

        // Should only active-records be filtered?
        if (filterOnActive == true) {

            // If so, then append the active-flag to the query's where clause
            customerListQuery.addConditionEq('Is_Active__c', true);

        }

        // Execute the query and evaluate the results
        customerLists = customerListQuery.run();

        // Process the return results in a consistent manner
        output = (B2C_CustomerList__c)processReturnResult('B2C_CustomerList__c', returnEmptyObject, customerLists, errorMsg);

        // Return the customerList result
        return output;

    }

    /**
     * @description Attempts to retrieve a customer list configured via custom objects.
     *
     * @param customerListId {String} Describes the CRM customerList identifier used to retrieve a given definition
     * @param filterOnActive {Boolean} Describes if the query should filter on active objects only
     * @param returnEmptyObject {Boolean} Describes if an empty sObject should be returned if no results are found
     * @return B2C Returns an instance of the customer list
     */
    public static B2C_CustomerList__c getCustomerListById(String customerListId, Boolean filterOnActive, Boolean returnEmptyObject) {

        // Initialize local variables
        List<B2C_CustomerList__c> customerLists;
        String errorMsg;
        Query customerListQuery;
        B2C_CustomerList__c output;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_CustomerListNotFound, customerListId);

        // Seed the default query structure to leverage
        customerListQuery = getDefaultQuery();

        // Define the record limit for the query
        customerListQuery.setLimit(1);

        // Define the default where-clause for the query
        customerListQuery.addConditionEq('Id', customerListId);

        // Should only active-records be filtered?
        if (filterOnActive == true) {

            // If so, then append the active-flag to the query's where clause
            customerListQuery.addConditionEq('Is_Active__c', true);

        }

        // Execute the query and evaluate the results
        customerLists = customerListQuery.run();

        // Process the return results in a consistent manner
        output = (B2C_CustomerList__c)processReturnResult('B2C_CustomerList__c', returnEmptyObject, customerLists, errorMsg);

        // Return the customerList result
        return output;

    }

    /**
     * @description Helper method that provides a consistent set of columns to leverage
     * when selecting sObject data via SOQL
     *
     * @return {Query} Returns the query template to leverage for customerLists
     */
    private static Query getDefaultQuery() {

        // Initialize local variables
        Query customerListQuery;

        // Create the profile query that will be used to drive resolution
        customerListQuery = new Query('B2C_CustomerList__c');

        // Add the fields to retrieve
        customerListQuery.selectField('Id');
        customerListQuery.selectField('Name');
        customerListQuery.selectField('B2C_Instance__c');
        customerListQuery.selectField('API_Url__c');
        customerListQuery.selectField('Base_API_Url__c');
        customerListQuery.selectField('OCAPI_Version_No__c');
        customerListQuery.selectField('Named_Credential_Developer_Name__c');
        customerListQuery.selectField('Audit_OCAPI_API_Response__c');
        customerListQuery.selectField('Is_Active__c');
        customerListQuery.selectField('Default_Storefront__c');
        customerListQuery.selectField('Enable_Profile_Retrieval__c');
        customerListQuery.selectField('Enable_Profile_Publishing__c');
        customerListQuery.selectField('Enable_Profile_Creation__c');
        customerListQuery.selectField('Enable_Profile_Updates__c');

        // Return the default query structure
        return customerListQuery;

    }

}