src/sfdc/base/main/default/objects/B2C_AuthToken__c/B2C_AuthToken__c.object-meta.xml
<CustomObject>
    <description>... represents the B2C AuthTokens used to enable REST API access associated with NamedCredentials and B2C ClientIDs.</description>
    <label>B2C AuthToken</label>
    <nameField>
        <displayFormat>B2CAT-{0000}</displayFormat>
        <label>B2C Auth Token</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2C AuthTokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_AuthToken__c/fields/B2C_AuthToken__c.field-meta.xml
<CustomField>
    <fullName>B2C_AuthToken__c</fullName>
    <description>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</description>
    <inlineHelpText>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</inlineHelpText>
    <label>B2C AuthToken</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_AuthToken__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</description>
    <inlineHelpText>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/B2C_Client_ID_Integration_History__c.object-meta.xml
<CustomObject>
    <description>... represents the B2C Commerce Account Manager authentication request history for a given B2C Client ID.</description>
    <label>B2C Client ID Integration History</label>
    <nameField>
        <displayFormat>B2CCID-{0000}</displayFormat>
        <label>Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2C Client ID Integration History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Account_Manager_Url__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Url__c</fullName>
    <description>... represents the full Url that was used to invoke the authentication request.</description>
    <inlineHelpText>... represents the full Url that was used to invoke the authentication request.</inlineHelpText>
    <label>Account Manager Url</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Auth_Token_Value__c.field-meta.xml
<CustomField>
    <fullName>Auth_Token_Value__c</fullName>
    <description>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</description>
    <inlineHelpText>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</inlineHelpText>
    <label>Auth Token Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/B2C_AuthToken__c.field-meta.xml
<CustomField>
    <fullName>B2C_AuthToken__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the AuthToken provided by the B2C Commerce Account Manager that can be used to power B2C Commerce REST API requests.</description>
    <inlineHelpText>... represents the AuthToken provided by the B2C Commerce Account Manager that can be used to power B2C Commerce REST API requests.</inlineHelpText>
    <label>B2C AuthToken</label>
    <referenceTo>B2C_AuthToken__c</referenceTo>
    <relationshipLabel>B2C Client ID Integration History</relationshipLabel>
    <relationshipName>B2C_Client_ID_Integration_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the B2C Client ID that used for a given B2C Commerce Account Manager authentication request.</description>
    <inlineHelpText>... represents the B2C Client ID that used for a given B2C Commerce Account Manager authentication request.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C Client ID Integration History</relationshipLabel>
    <relationshipName>B2C_Client_ID_Integration_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Has_Error__c.field-meta.xml
<CustomField>
    <fullName>Has_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes in the last processed integration attempt generated an error.</description>
    <inlineHelpText>... describes in the last processed integration attempt generated an error.</inlineHelpText>
    <label>Has Error</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Has_Token__c.field-meta.xml
<CustomField>
    <fullName>Has_Token__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if an authToken was provided in the response by the B2C Commerce Account Manager.</description>
    <inlineHelpText>... describes if an authToken was provided in the response by the B2C Commerce Account Manager.</inlineHelpText>
    <label>Has Token</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Integration_JSON__c.field-meta.xml
<CustomField>
    <fullName>Integration_JSON__c</fullName>
    <description>... describes the last JSON response provided by the B2C Commerce Account Manager for a given authentication request.</description>
    <inlineHelpText>... describes the last JSON response provided by the B2C Commerce Account Manager for a given authentication request.</inlineHelpText>
    <label>Integration JSON</label>
    <length>64000</length>
    <type>LongTextArea</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Integration_Message__c.field-meta.xml
<CustomField>
    <fullName>Integration_Message__c</fullName>
    <description>... represents an ad-hoc integration message attached to source objects via the last triggered platformEvent.</description>
    <inlineHelpText>... represents an ad-hoc integration message attached to source objects via the last triggered platformEvent.</inlineHelpText>
    <label>Integration Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Integration_Payload__c.field-meta.xml
<CustomField>
    <fullName>Integration_Payload__c</fullName>
    <description>... describes the last authorization request payload delivered to the B2C Commerce Account Manager.</description>
    <inlineHelpText>... describes the last authorization request payload delivered to the B2C Commerce Account Manager.</inlineHelpText>
    <label>Integration Payload</label>
    <length>64000</length>
    <type>LongTextArea</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>... represents the httpStatus code last recorded when record-detail integration was processed.</description>
    <inlineHelpText>... represents the httpStatus code last recorded when record-detail integration was processed.</inlineHelpText>
    <label>Status Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CIAPersistB2CAuthToken.cls
/**
 * @author Abraham David Lloyd
 * @date June 22nd, 2021
 *
 * @description This is a helper invocable-action designed to persist B2C AuthTokens and
 * audit their creation (provides logging specific to the creation of authTokens).
*/
//noinspection ApexUnusedDeclaration
public with sharing class B2CIAPersistB2CAuthToken {

    /**
     * @see B2CIARequestB2CAuthToken.getB2CAuthTokenViaJWT
     * @description Helper method to persist authTokens and their audit histories.  We expose this as a queueable
     * method so that we can include it in-between REST API call-outs that are exposed in our flows.
     *
     * @param authTokenResults {List<B2CIARequestB2CAuthTokenResult>} Represents the persisted authToken results
     */
    @InvocableMethod(Label='B2C: Persist and Audit B2C AuthToken' Description='Attempts to persist and audit any B2C AuthTokens requested from the B2C Commerce Account Manager environment.')
    public static void persistAndAuditB2CAuthToken(List<B2CIARequestB2CAuthTokenResult> authTokenResults) {

        // Initialize local variables
        Map<String, String> accountManagerConfigSettings;
        List<B2C_AuthToken__c> authTokens;
        B2C_AuthToken__c authToken;
        List<B2C_Client_ID_Integration_History__c> integrationHistory;
        B2C_Client_ID_Integration_History__c integrationHistoryEntry;
        Boolean hasB2CAuthToken;
        Map<String, String> authTokenIds;
        Integer integrationHistoryEntryIndex;

        // Get the JWT default configuration values
        accountManagerConfigSettings = B2CConfigurationManager.getAccountManagerSettings();

        // Initialize the authTokens collection(s)
        authTokens = new List<B2C_AuthToken__c>();
        authTokenIds = new Map<String, String>();
        integrationHistory = new List<B2C_Client_ID_Integration_History__c>();
        integrationHistoryEntryIndex = 0;

        // Loop over the collection of authToken results
        for (B2CIARequestB2CAuthTokenResult thisAuthTokenResult : authTokenResults) {

            // If we should bypass authToken auditing -- continue and exit-early
            if (thisAuthTokenResult.bypassAuthTokenAuditing == true) { continue; }

            // Shorthand B2C AuthToken validation
            hasB2CAuthToken = (thisAuthTokenResult.accessToken == null) ? false : true;

            // Should the authToken be persisted?
            if (thisAuthTokenResult.persistAuthToken == true) {

                // Was a B2C AuthToken returned?
                if (hasB2CAuthToken) {

                    // If so, create an instance of the authToken
                    authToken = new B2C_AuthToken__c(
                        B2C_Client_ID__c = thisAuthTokenResult.b2cClientIdRecordId,
                        B2C_AuthToken__c = thisAuthTokenResult.accessToken
                    );

                    // Create the collection of authTokens to process
                    authTokens.add(authToken);

                }

                // Is auditing enabled for the current authToken?
                if (thisAuthTokenResult.auditAuthenticationAPIInteractions == true) {

                    // Create the integration history entry for the authToken request
                    integrationHistoryEntry = new B2C_Client_ID_Integration_History__c(
                        B2C_Client_ID__c = thisAuthTokenResult.b2cClientIdRecordId,
                        Auth_Token_Value__c = thisAuthTokenResult.accessToken,
                        Account_Manager_Url__c = thisAuthTokenResult.accountManagerUrl,
                        Status_Code__c = thisAuthTokenResult.statusCode,
                        Has_Token__c = (thisAuthTokenResult.accessToken == null) ? false : true,
                        Has_Error__c = thisAuthTokenResult.isError,
                        Integration_Message__c = thisAuthTokenResult.errorMessage,
                        Integration_Payload__c = thisAuthTokenResult.requestBody,
                        Integration_JSON__c = thisAuthTokenResult.responseBody
                    );

                    // Add the current integration history entry to the over-arching history
                    integrationHistory.add(integrationHistoryEntry);

                }

            }

        }

        // Was at least one (1) authToken processed?
        if (authTokens.size() > 0 &&
            B2C_AuthToken__c.SObjectType.getDescribe().isAccessible() &&
            B2C_AuthToken__c.SObjectType.getDescribe().isCreateable()) {

            // Insert the authTokens and collect the results
            insert(authTokens);

            // Create the authTokenId map / Id quickReference
            for (B2C_AuthToken__c thisAuthToken : authTokens) {
                authTokenIds.put(thisAuthToken.B2C_AuthToken__c, thisAuthToken.Id);
            }

        }

        // Was at least (1) authToken integration event audited?
        if (integrationHistory.size() > 0 &&
            B2C_Client_ID_Integration_History__c.SObjectType.getDescribe().isAccessible() &&
            B2C_Client_ID_Integration_History__c.SObjectType.getDescribe().isCreateable()) {

            // Loop over the collection of integrationHistory entries
            for (B2C_Client_ID_Integration_History__c thisIntegrationHistoryEntry : integrationHistory) {

                // Assign the authToken identifier using the tokenValue as a reference point
                thisIntegrationHistoryEntry.B2C_AuthToken__c = authTokenIds.get(thisIntegrationHistoryEntry.Auth_Token_Value__c);

                // Re-seed the integrationHistory entry back in its ordinal position
                integrationHistory.set(integrationHistoryEntryIndex, thisIntegrationHistoryEntry);

                // Increase the integrationHistory index
                integrationHistoryEntryIndex ++;

            }

            // Insert the collection of history entries
            insert(integrationHistory);

        }

    }

}