src/sfdc/base/main/default/objects/B2C_AuthToken__c/B2C_AuthToken__c.object-meta.xml
<CustomObject>
    <description>... represents the B2C AuthTokens used to enable REST API access associated with NamedCredentials and B2C ClientIDs.</description>
    <label>B2C AuthToken</label>
    <nameField>
        <displayFormat>B2CAT-{0000}</displayFormat>
        <label>B2C Auth Token</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2C AuthTokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_AuthToken__c/fields/B2C_AuthToken__c.field-meta.xml
<CustomField>
    <fullName>B2C_AuthToken__c</fullName>
    <description>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</description>
    <inlineHelpText>... represents the recorded B2C Commerce Account Manager AuthToken for a given authentication request.</inlineHelpText>
    <label>B2C AuthToken</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_AuthToken__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</description>
    <inlineHelpText>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/Audit_Authentication_API_Interactions__c.field-meta.xml
<CustomField>
    <fullName>Audit_Authentication_API_Interactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</description>
    <inlineHelpText>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</inlineHelpText>
    <label>Audit Authentication API Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID_Label__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID_Label__c</fullName>
    <description>... represents the customer-facing label / name for the B2C Client ID.</description>
    <inlineHelpText>... represents the customer-facing label / name for the B2C Client ID.</inlineHelpText>
    <label>B2C Client ID Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/B2C_Client_ID_Integration_History__c.object-meta.xml
<CustomObject>
    <description>... represents the B2C Commerce Account Manager authentication request history for a given B2C Client ID.</description>
    <label>B2C Client ID Integration History</label>
    <nameField>
        <displayFormat>B2CCID-{0000}</displayFormat>
        <label>Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B2C Client ID Integration History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/B2C_AuthToken__c.field-meta.xml
<CustomField>
    <fullName>B2C_AuthToken__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the AuthToken provided by the B2C Commerce Account Manager that can be used to power B2C Commerce REST API requests.</description>
    <inlineHelpText>... represents the AuthToken provided by the B2C Commerce Account Manager that can be used to power B2C Commerce REST API requests.</inlineHelpText>
    <label>B2C AuthToken</label>
    <referenceTo>B2C_AuthToken__c</referenceTo>
    <relationshipLabel>B2C Client ID Integration History</relationshipLabel>
    <relationshipName>B2C_Client_ID_Integration_History</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID_Integration_History__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the B2C Client ID that used for a given B2C Commerce Account Manager authentication request.</description>
    <inlineHelpText>... represents the B2C Client ID that used for a given B2C Commerce Account Manager authentication request.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C Client ID Integration History</relationshipLabel>
    <relationshipName>B2C_Client_ID_Integration_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CIAPersistB2CAuthToken_Test.cls
/**
 * @author Abraham David Lloyd
 * @date June 29th, 2021
 *
 * @description This class exercises the successful persistence of a B2C AuthToken and
 * its auditEvent details to the current Salesforce org.
 */
@IsTest
private class B2CIAPersistB2CAuthToken_Test {

    /**
     * @see B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken
     * @description This test is used to exercise the persistence of a B2C AuthToken and its
     * audit details for a specific B2C Client ID.
     */
    @IsTest
    static void testPersistAndAuditB2CAuthToken() {

        // Initialize local variables
        B2C_Client_ID__c testClientID;
        List<B2CIARequestB2CAuthTokenResult> authTokenResults;
        B2CIARequestB2CAuthTokenResult authTokenResult;

        // Initialize the results collection
        authTokenResults = new List<B2CIARequestB2CAuthTokenResult>();

        // Initialize the result we'll process
        authTokenResult = new B2CIARequestB2CAuthTokenResult();

        // Create the test ClientID
        testClientID = new B2C_Client_ID__c(
            Name = 'testClientID',
            B2C_Client_ID_Label__c = 'Test B2C ClientID',
            Audit_Authentication_API_Interactions__c = true,
            Is_Active__c = true,
            JWT_Certificate_Name__c = B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME
        );

        // Insert the ClientID
        Database.insert(testClientID);

        Test.startTest();

            // Define the authToken processing results details
            authTokenResult.b2cClientIdRecordId = testClientID.Id;
            authTokenResult.b2cClientId = testClientID.Name;
            authTokenResult.auditAuthenticationAPIInteractions = true;
            authTokenResult.bypassAuthTokenAuditing = false;
            authTokenResult.persistAuthToken = true;
            authTokenResult.status = 'OK';
            authTokenResult.statusCode = 200;
            authTokenResult.accessToken = 'my-access-token';
            authTokenResult.tokenType = 'Bearer';
            authTokenResult.expiresIn = 1799;
            authTokenResult.accountManagerUrl = 'https://account.demandware.com/dw/sso/access_token';
            authTokenResult.requestBody = 'my-test-body';
            authTokenResult.responseBody = '{ "my-test-result": true }';
            authTokenResult.isError = false;
            authTokenResult.errorMessage = null;

            // Execute the authToken processor and persist / audit
            B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken(
              new List<B2CIARequestB2CAuthTokenResult> {
                  authTokenResult
              }
            );

        Test.stopTest();

        // Retrieve the persisted authToken
        List<B2C_AuthToken__c> testAuthToken = [
            SELECT  Id
            FROM    B2C_AuthToken__c
            WHERE   B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
            LIMIT   1
        ];

        // Retrieve the audit-record
        List<B2C_Client_ID_Integration_History__c> testIntegrationHistory = [
            SELECT  Id
            FROM    B2C_Client_ID_Integration_History__c
            WHERE   B2C_AuthToken__c = :testAuthToken.get(0).Id
            AND     B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
        ];

        // Validate that the authToken and the integration history record(s) were persisted
        System.assert(testAuthToken.size() == 1, 'Expected an authToken to be persisted and mapped to the test B2C ClientID');
        System.assert(testIntegrationHistory.size() == 1, 'Expected an integrationHistory record to be persisted and mapped to the B2C AuthToken and ClientID');

    }

    /**
     * @see B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken
     * @description This test is used to exercise the persistence of a B2C AuthToken without
     * its audit details for a specific B2C Client ID.
     */
    @IsTest
    static void testPersistB2CAuthTokenNoAuditing() {

        // Initialize local variables
        B2C_Client_ID__c testClientID;
        List<B2CIARequestB2CAuthTokenResult> authTokenResults;
        B2CIARequestB2CAuthTokenResult authTokenResult;

        // Initialize the results collection
        authTokenResults = new List<B2CIARequestB2CAuthTokenResult>();

        // Initialize the result we'll process
        authTokenResult = new B2CIARequestB2CAuthTokenResult();

        // Create the test ClientID
        testClientID = new B2C_Client_ID__c(
            Name = 'testClientID',
            B2C_Client_ID_Label__c = 'Test B2C ClientID',
            Audit_Authentication_API_Interactions__c = false,
            Is_Active__c = true,
            JWT_Certificate_Name__c = B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME
        );

        // Insert the ClientID
        Database.insert(testClientID);

        Test.startTest();

            // Define the authToken processing results details
            authTokenResult.b2cClientIdRecordId = testClientID.Id;
            authTokenResult.b2cClientId = testClientID.Name;
            authTokenResult.auditAuthenticationAPIInteractions = false;
            authTokenResult.bypassAuthTokenAuditing = false;
            authTokenResult.persistAuthToken = true;
            authTokenResult.status = 'OK';
            authTokenResult.statusCode = 200;
            authTokenResult.accessToken = 'my-access-token';
            authTokenResult.tokenType = 'Bearer';
            authTokenResult.expiresIn = 1799;
            authTokenResult.accountManagerUrl = 'https://account.demandware.com/dw/sso/access_token';
            authTokenResult.requestBody = 'my-test-body';
            authTokenResult.responseBody = '{ "my-test-result": true }';
            authTokenResult.isError = false;
            authTokenResult.errorMessage = null;

            // Execute the authToken processor and persist / audit
            B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken(
                new List<B2CIARequestB2CAuthTokenResult> {
                    authTokenResult
                }
            );

        Test.stopTest();

        // Retrieve the persisted authToken
        List<B2C_AuthToken__c> testAuthToken = [
                SELECT  Id
                FROM    B2C_AuthToken__c
                WHERE   B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
                LIMIT   1
        ];

        // Retrieve the audit-record
        List<B2C_Client_ID_Integration_History__c> testIntegrationHistory = [
                SELECT  Id
                FROM    B2C_Client_ID_Integration_History__c
                WHERE   B2C_AuthToken__c = :testAuthToken.get(0).Id
                AND     B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
        ];

        // Validate that the authToken was persisted -- but that the integration history record was not created
        System.assert(testAuthToken.size() == 1, 'Expected an authToken to be persisted and mapped to the test B2C ClientID');
        System.assert(testIntegrationHistory.size() == 0, 'Expected no integrationHistory record to be persisted and mapped to the B2C AuthToken and ClientID');

    }

    /**
     * @see B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken
     * @description This test is used to exercise bypassing B2C AuthToken and integrationHistory
     * persistence (no record(s) are kept or maintained when the bypass is enabled).
     */
    @IsTest
    static void testBypassPersistB2CAuthToken() {

        // Initialize local variables
        B2C_Client_ID__c testClientID;
        List<B2CIARequestB2CAuthTokenResult> authTokenResults;
        B2CIARequestB2CAuthTokenResult authTokenResult;

        // Initialize the results collection
        authTokenResults = new List<B2CIARequestB2CAuthTokenResult>();

        // Initialize the result we'll process
        authTokenResult = new B2CIARequestB2CAuthTokenResult();

        // Create the test ClientID
        testClientID = new B2C_Client_ID__c(
            Name = 'testClientID',
            B2C_Client_ID_Label__c = 'Test B2C ClientID',
            Audit_Authentication_API_Interactions__c = true,
            Is_Active__c = true,
            JWT_Certificate_Name__c = B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME
        );

        // Insert the ClientID
        Database.insert(testClientID);

        Test.startTest();

        // Define the authToken processing results details
        authTokenResult.b2cClientIdRecordId = testClientID.Id;
        authTokenResult.b2cClientId = testClientID.Name;
        authTokenResult.auditAuthenticationAPIInteractions = true;
        authTokenResult.bypassAuthTokenAuditing = true;
        authTokenResult.persistAuthToken = true;
        authTokenResult.status = 'OK';
        authTokenResult.statusCode = 200;
        authTokenResult.accessToken = 'my-access-token';
        authTokenResult.tokenType = 'Bearer';
        authTokenResult.expiresIn = 1799;
        authTokenResult.accountManagerUrl = 'https://account.demandware.com/dw/sso/access_token';
        authTokenResult.requestBody = 'my-test-body';
        authTokenResult.responseBody = '{ "my-test-result": true }';
        authTokenResult.isError = false;
        authTokenResult.errorMessage = null;

        // Execute the authToken processor and persist / audit
        B2CIAPersistB2CAuthToken.persistAndAuditB2CAuthToken(
            new List<B2CIARequestB2CAuthTokenResult> {
                authTokenResult
            }
        );

        Test.stopTest();

        // Retrieve the persisted authToken
        List<B2C_AuthToken__c> testAuthToken = [
            SELECT  Id
            FROM    B2C_AuthToken__c
            WHERE   B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
            LIMIT   1
        ];

        // Retrieve the audit-record
        List<B2C_Client_ID_Integration_History__c> testIntegrationHistory = [
            SELECT  Id
            FROM    B2C_Client_ID_Integration_History__c
            WHERE   B2C_Client_ID__c = :authTokenResult.b2cClientIdRecordId
        ];

        // Validate that the authToken and integration history were not persisted
        System.assert(testAuthToken.size() == 0, 'Expected no authToken to be persisted and mapped to the test B2C ClientID');
        System.assert(testIntegrationHistory.size() == 0, 'Expected no integrationHistory record to be persisted and mapped to the B2C AuthToken and ClientID');

    }

}