src/sfdc/base/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</description>
    <inlineHelpText>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</inlineHelpText>
    <label>Enable Profile Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</description>
    <inlineHelpText>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</inlineHelpText>
    <label>Enable Profile Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Retrieval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Customer Profiles can be retrieved from B2C Commerce.</description>
    <inlineHelpText>... describes if Customer Profiles can be retrieved from B2C Commerce.</inlineHelpText>
    <label>Enable Profile Retrieval</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Updates__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</description>
    <inlineHelpText>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</inlineHelpText>
    <label>Enable Profile Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CIAValidateContact_Test.cls
/**
 * @author Eric Schultz
 * @date April 11th, 2021
 *
 * @description This test class exercises our validateContact logic.
*/
@IsTest
private class B2CIAValidateContact_Test {

    /**
     * @see B2CIAValidateContact.validateContact
     * @description This is used to confirm that we can validate a contactRecord successfully and determine
     * the integration status / available integration options for a given contact record.
     */
    @IsTest
    static void isValid() {

        // Initialize local variables
        List<B2CIAValidateContactInput> inputList = new List<B2CIAValidateContactInput>();
        B2CIAValidateContactInput input = new B2CIAValidateContactInput();
        List<B2CIAValidateContactResult> validationResult = new List<B2CIAValidateContactResult>();
        String errorMessage;

        // Default the errorMessage
        errorMessage = '-- Expected the integrationStatus to be true; integration should be enabled';

        // Define the contact that will be exercised
        input.contact = (Contact)TestDataFactory.createSObject(
            'Contact',
            new Map<String,Object>{
                'B2C_Disable_Integration__c' => false
             }
        );

        // Define the customerList that will parent the Contact
        input.customerList = (B2C_CustomerList__c)TestDataFactory.createSObject(
            'B2C_CustomerList__c',
            new Map<String,Object>{
                'API_URL__c' => 'https://www.salesforce.com',
                'B2C_Instance__r.API_URL__c' => 'https://www.salesforce.com',
                'Enable_Profile_Retrieval__c' => true,
                'Enable_Profile_Publishing__c' => true,
                'Enable_Profile_Creation__c' => true,
                'Enable_Profile_Updates__c' => true,
                'Is_Active__c' => true
            }
        );

        // Initialize the b2cInstance that will parent the customerList
        input.b2cInstance = (B2C_Instance__c)TestDataFactory.createSObject(
            'B2C_Instance__c',
            new Map<String,Object>{
                'API_URL__c' => 'https://www.salesforce.com',
                'Is_Active__c' => true
            }
        );

        // Define the processMode to employ
        input.processMode = B2CConstant.CONTACT_INTEGRATION_PROCESSMODE_RETRIEVE;

        // Add the invocableAction arguments to the parent collection
        inputList.add( input );

        Test.startTest();

            // Exercise the contactValidation action
            validationResult = B2CIAValidateContact.validateContact(inputList);

        Test.stopTest();

        // Validate that the testResults are successful
        for (B2CIAValidateContactResult thisValidationResult : validationResult) {

            // Assert that the integration status is enabled / active
            System.assert(thisValidationResult.allowIntegrationProcess, errorMessage);

        }

    }

    /**
     * @see B2CIAValidateContact.validateContact
     * @description This is used to confirm that we can validate a contactRecord successfully and determine
     * the integration status / available integration options for a given contact record.  This method
     * validates failures (we cannot integrate).
     */
    @IsTest
    static void isDisabled() {

        // Initialize local variables
        List<B2CIAValidateContactInput> inputList = new List<B2CIAValidateContactInput>();
        B2CIAValidateContactInput input = new B2CIAValidateContactInput();
        List<B2CIAValidateContactResult> validationResult = new List<B2CIAValidateContactResult>();
        String errorMessage;

        // Default the errorMessage
        errorMessage = '-- Expected the integrationStatus to be true; integration should be enabled';

        // Define the contact that will be exercised; disable integration
        input.contact = (Contact)TestDataFactory.createSObject(
            'Contact',
            new Map<String,Object>{
                'B2C_Disable_Integration__c' => true
            }
        );


        // Define the customerList that will parent the Contact
        input.customerList = (B2C_CustomerList__c)TestDataFactory.createSObject(
            'B2C_CustomerList__c',
            new Map<String,Object>{
                'API_URL__c' => 'https://www.salesforce.com',
                'B2C_Instance__r.API_URL__c' => 'https://www.salesforce.com',
                'Enable_Profile_Retrieval__c' => true,
                'Enable_Profile_Publishing__c' => true,
                'Enable_Profile_Creation__c' => true,
                'Enable_Profile_Updates__c' => true,
                'Is_Active__c' => true
            }
        );

        // Initialize the b2cInstance that will parent the customerList
        input.b2cInstance = (B2C_Instance__c)TestDataFactory.createSObject(
            'B2C_Instance__c',
            new Map<String,Object>{
                'API_URL__c' => 'https://www.salesforce.com',
                'Is_Active__c' => true
            }
        );

        // Define the processMode to employ
        input.processMode = B2CConstant.CONTACT_INTEGRATION_PROCESSMODE_RETRIEVE;

        // Add the invocableAction arguments to the parent collection
        inputList.add( input );

        Test.startTest();

            // Exercise the contactValidation action
            validationResult = B2CIAValidateContact.validateContact(inputList);

        Test.stopTest();

        // Validate that the testResults are successful
        for (B2CIAValidateContactResult thisValidationResult : validationResult) {

            // Assert that the integration status is enabled / active
            System.assertEquals(thisValidationResult.allowIntegrationProcess, false, errorMessage);

        }

    }

}