src/sfdc/base/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</description>
    <inlineHelpText>... describes whether B2C Commerce Profiles can be created for this CustomerList as Salesforce Platform Accounts / Contacts.</inlineHelpText>
    <label>Enable Profile Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</description>
    <inlineHelpText>... describes if Contact updates can be published from the Salesforce Platform to B2C Commerce.</inlineHelpText>
    <label>Enable Profile Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Retrieval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Customer Profiles can be retrieved from B2C Commerce.</description>
    <inlineHelpText>... describes if Customer Profiles can be retrieved from B2C Commerce.</inlineHelpText>
    <label>Enable Profile Retrieval</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Profile_Updates__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</description>
    <inlineHelpText>... describes if Account / Contact record updates can be initiated from B2C Commerce via REST APIs.</inlineHelpText>
    <label>Enable Profile Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/Updated_by_B2C_Platform_Event__c.field-meta.xml
<CustomField>
    <fullName>Updated_by_B2C_Platform_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... internal field that causes Contact updates to bypass the B2C Commerce Platform Event processing.</description>
    <inlineHelpText>... internal field that causes Contact updates to bypass the B2C Commerce Platform Event processing.</inlineHelpText>
    <label>Bypass B2C Commerce Platform Event</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CProcessContact_Test.cls
/**
 * @author Abraham David Lloyd
 * @date June 29th, 2021
 *
 * @description This class is to validate that the B2CProcessContact trigger behavior.
 */
@IsTest
private class B2CProcessContact_Test {

    /**
     * @description This test validates that the process trigger can update a
     * contact and process successfully when a contact lacks an Account and B2C
     * customerProfile identifiers.
     */
    @IsTest
    static void testCreateContactWithoutAccountB2CCustomerListCustomerNo() {

        // Initialize local variables
        Database.SaveResult processingResult;
        Boolean errorThrown = false;
        Contact testContact = new Contact(
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'anonymous@b2csa.qa.salesforce.com'
        );

        Test.startTest();

            try {

                // Create the Contact record
                Database.insert(testContact);

                // Update the email address for the testContact
                testContact.Email = 'anon@b2csa.qa.salesforce.com';

                // Process the update and invoke the trigger
                processingResult = Database.update(testContact);

            } catch (Exception e) {

                // Flag that an error was thrown
                errorThrown = true;

            }

        Test.stopTest();

        // Validate that the update was successfully processed
        System.assert(errorThrown == false, 'Expected this test to execute without an error being thrown');
        System.assert(processingResult.isSuccess() == true, 'Expected the update statement to be successful');

    }

    /**
     * @description This test validates that the process trigger can update a
     * contact and process successfully when a contact has an Account and lacks B2C
     * customerProfile identifiers.
     */
    @IsTest
    static void testUpdateContactWithAccountWithoutB2CCustomerListCustomerNo() {

        // Initialize local variables
        Database.SaveResult processingResult;
        Boolean errorThrown = false;

        // Initialize the Account / Contact details
        Account testAccount = new Account(
            Name = 'Anonymous Customer',
            RecordTypeId = B2CIACustomerResolution_TestHelper.getRecordType(B2CConfigurationManager.getAccountRecordTypeDeveloperName()).Id
        );

        // Create the parent Account record
        Database.insert(testAccount);

        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'anonymous@b2csa.qa.salesforce.com'
        );

        // Create the child Contact record
        Database.insert(testContact);

        Test.startTest();

            try {

                // Update the email address for the testContact
                testContact.Email = 'anon@b2csa.qa.salesforce.com';

                // Process the update and invoke the trigger
                processingResult = Database.update(testContact);

            } catch (Exception e) {

                // Flag that an error was thrown
                errorThrown = true;

            }

        Test.stopTest();

        // Validate that the update was successfully processed
        System.assert(errorThrown == false, 'Expected this test to execute without an error being thrown');
        System.assert(processingResult.isSuccess() == true, 'Expected the update statement to be successful');

    }

    /**
     * @description This test validates that the process trigger can update a
     * contact and process successfully when a contact has an Account and B2C
     * customerProfile identifiers.
     */
    @IsTest
    static void testUpdateContactWithAccountB2CCustomerListCustomerNo() {

        // Initialize local variables
        Database.SaveResult processingResult;
        Boolean errorThrown = false;

        // Initialize the B2C Instance details
        B2C_Instance__c testInstance = new B2C_Instance__c(
            Name = 'test-001',
            API_Url__c = 'https://www.example.com',
            Is_Active__c = true
        );

        // Create the instance record
        Database.insert(testInstance);

        // Initialize the B2C CustomerList details
        B2C_CustomerList__c testCustomerList = new B2C_CustomerList__c(
            Name = 'RefArch',
            B2C_Instance__c = testInstance.Id,
            API_Url__c = 'https://www.example.com',
            Is_Active__c = true,
            Enable_Profile_Creation__c = true,
            Enable_Profile_Publishing__c = true,
            Enable_Profile_Retrieval__c = true,
            Enable_Profile_Updates__c = true
        );

        // Create the customerList record
        Database.insert(testCustomerList);

        // Initialize the Account
        Account testAccount = new Account(
            Name = 'Anonymous Customer',
            RecordTypeId = B2CIACustomerResolution_TestHelper.getRecordType(B2CConfigurationManager.getAccountRecordTypeDeveloperName()).Id
        );

        // Create the Account record
        Database.insert(testAccount);

        // Initialize the Contact
        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            B2C_CustomerList__c = testCustomerList.Id,
            B2C_Customer_No__c = '9999999',
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'anonymous@b2csa.qa.salesforce.com'
        );

        // Create the Contact record
        Database.insert(testContact);

        Test.startTest();

            try {

                // Update the email address for the testContact
                testContact.Email = 'anon@b2csa.qa.salesforce.com';

                // Process the update and invoke the trigger
                processingResult = Database.update(testContact);

            } catch (Exception e) {

                // Flag that an error was thrown
                errorThrown = true;

            }

        Test.stopTest();

        // Validate that the update was successfully processed
        System.assert(errorThrown == false, 'Expected this test to execute without an error being thrown');
        System.assert(processingResult.isSuccess() == true, 'Expected the update statement to be successful');

    }

    /**
     * @description This test validates that the process trigger bypasses processing Contact
     * updates if the platformEvent flag is set to true (this prevents a circular loop).
     */
    @IsTest
    static void testBypassPlatformEventCreation() {

        // Initialize local variables
        Database.SaveResult processingResult;
        Boolean errorThrown = false;

        // Initialize the B2C Instance details
        B2C_Instance__c testInstance = new B2C_Instance__c(
            Name = 'test-001',
            API_Url__c = 'https://www.example.com',
            Is_Active__c = true
        );

        // Create the instance record
        Database.insert(testInstance);

        // Initialize the B2C CustomerList details
        B2C_CustomerList__c testCustomerList = new B2C_CustomerList__c(
            Name = 'RefArch',
            B2C_Instance__c = testInstance.Id,
            API_Url__c = 'https://www.example.com',
            Is_Active__c = true,
            Enable_Profile_Creation__c = true,
            Enable_Profile_Publishing__c = true,
            Enable_Profile_Retrieval__c = true,
            Enable_Profile_Updates__c = true
        );

        // Create the customerList record
        Database.insert(testCustomerList);

        // Initialize the Account
        Account testAccount = new Account(
            Name = 'Anonymous Customer',
            RecordTypeId = B2CIACustomerResolution_TestHelper.getRecordType(B2CConfigurationManager.getAccountRecordTypeDeveloperName()).Id
        );

        // Create the Account record
        Database.insert(testAccount);

        // Initialize the Contact
        Contact testContact = new Contact(
            AccountId = testAccount.Id,
            B2C_CustomerList__c = testCustomerList.Id,
            B2C_Customer_No__c = '9999999',
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'anonymous@b2csa.qa.salesforce.com'
        );

        // Create the Contact record
        Database.insert(testContact);

        Test.startTest();

            try {

                // Update the email address for the testContact
                testContact.Email = 'anon@b2csa.qa.salesforce.com';
                testContact.Updated_by_B2C_Platform_Event__c = true;

                // Process the update and invoke the trigger
                processingResult = Database.update(testContact);

            } catch (Exception e) {

                // Flag that an error was thrown
                errorThrown = true;

            }

        Test.stopTest();

        // Validate that the update was successfully processed
        System.assert(errorThrown == false, 'Expected this test to execute without an error being thrown');
        System.assert(processingResult.isSuccess() == true, 'Expected the update statement to be successful');

    }


}