src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/B2C_CRM_Sync_AuthToken_Settings__mdt.object-meta.xml
<CustomObject>
    <description>... represents the collection of configuration settings used to create digitally signed JWT tokens that can be redeemed for REST API AuthTokens via B2C Commerce&apos;s Account Manager.</description>
    <label>B2C CRM Sync AuthToken Settings</label>
    <pluralLabel>B2C CRM Sync AuthToken Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Account_Manager_Port__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Port__c</fullName>
    <defaultValue>443</defaultValue>
    <description>... represents the http-port that will be used when rendering the Account Manager audienceUrl.</description>
    <inlineHelpText>... represents the http-port that will be used when rendering the Account Manager audienceUrl.</inlineHelpText>
    <label>Account Manager Port</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Account_Manager_Token_Url__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Token_Url__c</fullName>
    <description>... represents the urlSuffix used to request B2C Commerce REST API AuthTokens from Account Manager.</description>
    <inlineHelpText>... represents the urlSuffix used to request B2C Commerce REST API AuthTokens from Account Manager.</inlineHelpText>
    <label>Account Manager Token UrlSuffix</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Account_Manager_Url__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Url__c</fullName>
    <description>... represents the base url for B2C Commerce&apos;s Account Manager.</description>
    <inlineHelpText>... represents the base url for B2C Commerce&apos;s Account Manager.</inlineHelpText>
    <label>Account Manager Url</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Expiration_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Expiration_in_Minutes__c</fullName>
    <defaultValue>25</defaultValue>
    <description>... represents the number of minutes to use when calculating an expiration date for a minted JWT / authToken.</description>
    <inlineHelpText>... represents the number of minutes to use when calculating an expiration date for a minted JWT / authToken.</inlineHelpText>
    <label>Expiration in Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/JWT_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>JWT_Algorithm__c</fullName>
    <description>... represents the collection of algorithms to select from and specify in a JWT header when minting a JWT.</description>
    <inlineHelpText>... represents the collection of algorithms to select from and specify in a JWT header when minting a JWT.</inlineHelpText>
    <label>JWT SFDC Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RSA-SHA256</fullName>
                <default>true</default>
                <label>RSA-SHA256</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/JWT_SFCC_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>JWT_SFCC_Algorithm__c</fullName>
    <description>... represents the algorithm identifier leveraged by the B2C Commerce Account Manager to process a JWT token minted by the Salesforce Platform.  This identifier is embedded in the JWT.</description>
    <inlineHelpText>... represents the algorithm identifier leveraged by the B2C Commerce Account Manager to process a JWT token minted by the Salesforce Platform.  This identifier is embedded in the JWT.</inlineHelpText>
    <label>JWT SFCC Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RS256</fullName>
                <default>true</default>
                <label>RS256</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Persist_B2C_AuthTokens__c.field-meta.xml
<CustomField>
    <fullName>Persist_B2C_AuthTokens__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked, retrieved B2C AuthTokens will be persisted and audited for future re-use.</description>
    <inlineHelpText>... when checked, retrieved B2C AuthTokens will be persisted and audited for future re-use.</inlineHelpText>
    <label>Persist B2C AuthTokens</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <description>... represents the number of retries that should be performed when retrieving an authToken from the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the number of retries that should be performed when retrieving an authToken from the B2C Commerce Account Manager.</inlineHelpText>
    <label>Retry Count</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/B2C_CRM_Sync_Default_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>... represents the default configuration used to manage the configuration leveraged during production operation.</description>
    <label>B2C CRM Sync Default Configuration</label>
    <pluralLabel>B2C CRM Sync Default Configuration</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/fields/Active_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Active_Configuration__c</fullName>
    <description>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</description>
    <inlineHelpText>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</inlineHelpText>
    <label>Active Configuration</label>
    <referenceTo>B2C_CRMSync_Setting__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Default Configuration</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Default_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/B2C_CRMSync_Setting__mdt.object-meta.xml
<CustomObject>
    <description>... global configuration settings for B2C CRM Sync; manages instances of configuration settings for the B2C Commerce integration package.</description>
    <label>B2C CRM Sync Configuration Settings</label>
    <pluralLabel>B2C CRM Sync Configuration Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Account_Contact_Model__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact_Model__c</fullName>
    <label>Account Contact Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
                <default>true</default>
                <label>Person</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Account_Record_Type_Developername__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Type_Developername__c</fullName>
    <description>... represents the default recordType to use when creating a Parent Account for a given B2C Contact.</description>
    <inlineHelpText>... represents the default recordType to use when creating a Parent Account for a given B2C Contact.</inlineHelpText>
    <label>Account Record Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/B2C_CRM_Sync_AuthToken_Settings__c.field-meta.xml
<CustomField>
    <fullName>B2C_CRM_Sync_AuthToken_Settings__c</fullName>
    <description>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</description>
    <inlineHelpText>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</inlineHelpText>
    <label>B2C CRM Sync AuthToken Settings</label>
    <referenceTo>B2C_CRM_Sync_AuthToken_Settings__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Configuration Settings</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Configuration_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Account_Name__c</fullName>
    <description>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</inlineHelpText>
    <label>Default Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact_Name__c</fullName>
    <description>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</inlineHelpText>
    <label>Default Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_B2C_Process_Contact_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_B2C_Process_Contact_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</description>
    <inlineHelpText>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</inlineHelpText>
    <label>Enable B2C Process Contact Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_Client_ID_CertValidation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Client_ID_CertValidation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</description>
    <inlineHelpText>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</inlineHelpText>
    <label>Enable Client ID CertValidation Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/PersonAccount_Record_Type_Developername__c.field-meta.xml
<CustomField>
    <fullName>PersonAccount_Record_Type_Developername__c</fullName>
    <description>... represents the default recordType to use when creating a Person Account for a given B2C Contact.</description>
    <inlineHelpText>... represents the default recordType to use when creating a Person Account for a given B2C Contact.</inlineHelpText>
    <label>PersonAccount Record Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CConfigurationManager.cls
/**
 * @author Abraham David Lloyd
 * @date February 14th, 2021
 *
 * @description This class is used to retrieve the default configuration settings
 * for the B2C CRM Sync application.
 */
public with sharing class B2CConfigurationManager {

    /**
     * @description Helper function retrieves the associated Account Manager / JWT authentication
     * configuration settings that are related to the active configuration.
     * @return {Map<String, String>} Returns a map containing the related accountManager configuration settings
     */
    public static Map<String, String> getAccountManagerSettings() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Map<String, String> output;

        // Initialize the output map
        output = new Map<String, String>();

        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRM_Sync_Default_Configuration__mdt.fields.DeveloperName.isAccessible() &&
            B2C_CRMSync_Setting__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Account_Record_Type_Developername__c.isAccessible()
        ) {
            // Get the default configuration profile
            configurationProfile = [
                    SELECT  Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Port__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Token_Url__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Expiration_in_Minutes__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_Algorithm__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_SFCC_Algorithm__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Retry_Count__c,
                            Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Persist_B2C_AuthTokens__c
                    FROM    B2C_CRM_Sync_Default_Configuration__mdt
                    WHERE   DeveloperName = 'Production_Configuration'
                    LIMIT   1
            ];

            // Set the output variable to contain the Account Manager configuration settings to leverage
            output.put('AccountManagerUrl', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c);
            output.put('AccountManagerPort', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Port__c);
            output.put('AccountManagerSuffix', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Token_Url__c);
            output.put('ExpirationInMinutes', String.valueOf(configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Expiration_in_Minutes__c));
            output.put('JWTSFDCAlgorithm', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_Algorithm__c);
            output.put('JWTSFCCAlgorithm', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_SFCC_Algorithm__c);
            output.put('RetryCount', String.valueOf(configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Retry_Count__c));
            output.put('PersistAuthTokens', String.valueOf(configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Persist_B2C_AuthTokens__c));
        }

        // Return the associated Account Manager configuration settings
        return output;

    }

    /**
     * @description Helper function retrieves the default businessAccount
     * developerName used for accounts / contacts.
     * @return {String} Returns the developerName for the B2c Business Account
     */
    public static String getAccountRecordTypeDeveloperName() {
        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRM_Sync_Default_Configuration__mdt.fields.DeveloperName.isAccessible() &&
            B2C_CRMSync_Setting__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Account_Record_Type_Developername__c.isAccessible()
        ) {
            // Get the default configuration profile
            B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
                SELECT Active_Configuration__r.Account_Record_Type_Developername__c
                FROM B2C_CRM_Sync_Default_Configuration__mdt
                WHERE DeveloperName = 'Production_Configuration'
                LIMIT 1
            ];

            return configurationProfile.Active_Configuration__r.Account_Record_Type_Developername__c;

        }

        return null;

    }

    /**
     * @description Helper function retrieves the default personAccount
     * developerName used for accounts / contacts.
     * @return {String} Returns the developerName for the B2c Person Account
     */
    public static String getPersonAccountRecordTypeDeveloperName() {
        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRM_Sync_Default_Configuration__mdt.fields.DeveloperName.isAccessible() &&
            B2C_CRMSync_Setting__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.PersonAccount_Record_Type_Developername__c.isAccessible()
        ) {
            // Get the default configuration profile
            B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
                SELECT Active_Configuration__r.PersonAccount_Record_Type_Developername__c
                FROM B2C_CRM_Sync_Default_Configuration__mdt
                WHERE DeveloperName = 'Production_Configuration'
                LIMIT 1
            ];

            // Set the output variable to contain the specified configuration property
            return configurationProfile.Active_Configuration__r.PersonAccount_Record_Type_Developername__c;
        }

        return null;
    }

    /**
     * @description Helper function retrieves the default customerModel based on the
     * configuration profile that is configured.
     * @return {String} Returns the configured customerModel (Standard or Person).
     */
    public static String getDefaultAccountContactModel() {
        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRM_Sync_Default_Configuration__mdt.fields.DeveloperName.isAccessible() &&
            B2C_CRMSync_Setting__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Account_Contact_Model__c.isAccessible()
        ) {
            // Get the default configuration profile
            B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
                SELECT Active_Configuration__r.Account_Contact_Model__c
                FROM B2C_CRM_Sync_Default_Configuration__mdt
                WHERE DeveloperName = 'Production_Configuration'
                LIMIT 1
            ];

            return configurationProfile.Active_Configuration__r.Account_Contact_Model__c;

        }

        return null;

    }

    /**
     * @description Helper function that returns the default Account / Contact names.
     * @return {Map<String, String>} Returns the names used to default the Account Name
     * and Contact lastName during the resolution and contact-creation process
     */
    public static Map<String, String> getDefaultAccountContactNames() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Map<String, String> output;

        // Initialize the output map
        output = new Map<String, String>();

        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRM_Sync_Default_Configuration__mdt.fields.DeveloperName.isAccessible() &&
            B2C_CRMSync_Setting__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Default_Account_Name__c.isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Default_Contact_Name__c.isAccessible()
        ) {

            // Get the default configuration profile
            configurationProfile = [
                SELECT  Active_Configuration__r.Default_Account_Name__c,
                        Active_Configuration__r.Default_Contact_Name__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
            ];

            // Capture and seed the default account / contact names
            output.put('accountName', configurationProfile.Active_Configuration__r.Default_Account_Name__c);
            output.put('contactName', configurationProfile.Active_Configuration__r.Default_Contact_Name__c);

        }

        // Return the output property
        return output;

    }

    /**
     * @description Helper function that retrieves the current default configuration.
     * @return {Boolean} Returns the enabled / active status of the B2C Process Contact trigger
     */
    public static Boolean isB2CProcessContactTriggerEnabled() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Boolean output;

        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.DeveloperName.isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.MasterLabel.isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Enable_B2C_Process_Contact_Trigger__c.isAccessible()
        ) {

            // Get the default configuration profile
            configurationProfile = [
                SELECT  Active_Configuration__r.DeveloperName,
                        Active_Configuration__r.MasterLabel,
                        Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
            ];

            // Return the enabled status of the B2C ProcessContact Trigger
            output = configurationProfile.Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c;

        }

        // Return the output value
        return output;

    }

    /**
     * @description Helper function that retrieves the current default configuration.
     * @return {Boolean} Returns the enabled / active status of the B2C ClientID CertValidation trigger
     */
    public static Boolean isB2CClientIDCertValidationTriggerEnabled() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Boolean output;

        if (
            // Validate that we have CRUD permissions to access this data
            B2C_CRM_Sync_Default_Configuration__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.DeveloperName.isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.MasterLabel.isAccessible() &&
            Schema.SObjectType.B2C_CRMSync_Setting__mdt.fields.Enable_B2C_Process_Contact_Trigger__c.isAccessible()
        ) {

            // Get the default configuration profile
            configurationProfile = [
                SELECT  Active_Configuration__r.DeveloperName,
                        Active_Configuration__r.MasterLabel,
                        Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
            ];

            // Return the enabled status of the B2C Client ID certValidation trigger
            output = configurationProfile.Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c;

        }

        // Return the output value
        return output;

    }

}