src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/B2C_CRM_Sync_AuthToken_Settings__mdt.object-meta.xml
<CustomObject>
    <description>... represents the collection of configuration settings used to create digitally signed JWT tokens that can be redeemed for REST API AuthTokens via B2C Commerce&apos;s Account Manager.</description>
    <label>B2C CRM Sync AuthToken Settings</label>
    <pluralLabel>B2C CRM Sync AuthToken Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/B2C_CRM_Sync_Default_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>... represents the default configuration used to manage the configuration leveraged during production operation.</description>
    <label>B2C CRM Sync Default Configuration</label>
    <pluralLabel>B2C CRM Sync Default Configuration</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/fields/Active_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Active_Configuration__c</fullName>
    <description>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</description>
    <inlineHelpText>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</inlineHelpText>
    <label>Active Configuration</label>
    <referenceTo>B2C_CRMSync_Setting__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Default Configuration</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Default_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/B2C_CRMSync_Setting__mdt.object-meta.xml
<CustomObject>
    <description>... global configuration settings for B2C CRM Sync; manages instances of configuration settings for the B2C Commerce integration package.</description>
    <label>B2C CRM Sync Configuration Settings</label>
    <pluralLabel>B2C CRM Sync Configuration Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/B2C_CRM_Sync_AuthToken_Settings__c.field-meta.xml
<CustomField>
    <fullName>B2C_CRM_Sync_AuthToken_Settings__c</fullName>
    <description>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</description>
    <inlineHelpText>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</inlineHelpText>
    <label>B2C CRM Sync AuthToken Settings</label>
    <referenceTo>B2C_CRM_Sync_AuthToken_Settings__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Configuration Settings</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Configuration_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Account_Name__c</fullName>
    <description>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</inlineHelpText>
    <label>Default Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact_Name__c</fullName>
    <description>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</inlineHelpText>
    <label>Default Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_B2C_Process_Contact_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_B2C_Process_Contact_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</description>
    <inlineHelpText>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</inlineHelpText>
    <label>Enable B2C Process Contact Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_Client_ID_CertValidation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Client_ID_CertValidation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</description>
    <inlineHelpText>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</inlineHelpText>
    <label>Enable Client ID CertValidation Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CConfigurationManager_Test.cls
/**
 * @author Abraham David Lloyd
 * @date May 25th 2021
 *
 * @description This class is used exercise the configurationManager class and access the
 * configuration settings for b2c-crm-sync.
 */
@IsTest
public with sharing class B2CConfigurationManager_Test {

    @IsTest
    public static void getAccountManagerSettingsTest() {

        // Get the default configuration profile
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
            SELECT  Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c,
                    Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Port__c,
                    Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Token_Url__c,
                    Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Expiration_in_Minutes__c,
                    Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_Algorithm__c,
                    Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_SFCC_Algorithm__c
            FROM    B2C_CRM_Sync_Default_Configuration__mdt
            WHERE   DeveloperName = 'Production_Configuration'
            LIMIT   1
        ];

        Test.startTest();

            Map<String, String> accountManagerSettings = B2CConfigurationManager.getAccountManagerSettings();

        Test.stopTest();

        System.assertEquals(
            configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c,
            accountManagerSettings.get('AccountManagerUrl'),
            'Could not verify accountManagerUrl via the getAccountManagerSettings() method.'
        );

    }

    @IsTest
    public static void getDefaultAccountContactNames() {

        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
            SELECT  Active_Configuration__r.Default_Account_Name__c,
                    Active_Configuration__r.Default_Contact_Name__c
            FROM    B2C_CRM_Sync_Default_Configuration__mdt
            WHERE   DeveloperName = 'Production_Configuration'
            LIMIT   1
        ];

        Test.startTest();

            Map<String, String> defaultAccountContactNames = B2CConfigurationManager.getDefaultAccountContactNames();

        Test.stopTest();

        System.assertEquals(
            configurationProfile.Active_Configuration__r.Default_Account_Name__c,
            defaultAccountContactNames.get('accountName'),
            'Could not verify that the systemConfiguration accountName is retrievable via the configurationManager'
        );

        System.assertEquals(
            configurationProfile.Active_Configuration__r.Default_Contact_Name__c,
            defaultAccountContactNames.get('contactName'),
            'Could not verify that the systemConfiguration contactName is retrievable via the configurationManager'
        );
    }

    @IsTest
    public static void isB2CProcessContactTriggerEnabled() {
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
            SELECT  Active_Configuration__r.DeveloperName,
                    Active_Configuration__r.MasterLabel,
                    Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c
            FROM    B2C_CRM_Sync_Default_Configuration__mdt
            WHERE   DeveloperName = 'Production_Configuration'
            LIMIT   1
        ];

        Test.startTest();

            Boolean isB2CProcessContactTriggerEnabled = B2CConfigurationManager.isB2CProcessContactTriggerEnabled();

        Test.stopTest();

        System.assertEquals(
            configurationProfile.Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c,
            isB2CProcessContactTriggerEnabled,
            'Could not verify that the B2CProcessContact configuration setting is retrievable via the configurationManager'
        );

    }

    @IsTest
    public static void isJWTCertValidationTriggerEnabled() {
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile = [
            SELECT  Active_Configuration__r.DeveloperName,
                    Active_Configuration__r.MasterLabel,
                    Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c
            FROM    B2C_CRM_Sync_Default_Configuration__mdt
            WHERE   DeveloperName = 'Production_Configuration'
            LIMIT   1
        ];

        Test.startTest();

            Boolean triggerConfigValue = B2CConfigurationManager.isB2CClientIDCertValidationTriggerEnabled();

        Test.stopTest();

        System.assertEquals(
            configurationProfile.Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c,
            triggerConfigValue,
            'Could not verify that the jwtCertificateValidation configuration setting is retrievable via the configurationManager'
        );

    }

}