src/sfdc/base/main/default/objects/B2C_CRM_Sync_AuthToken_Settings__mdt/B2C_CRM_Sync_AuthToken_Settings__mdt.object-meta.xml
<CustomObject>
    <description>... represents the collection of configuration settings used to create digitally signed JWT tokens that can be redeemed for REST API AuthTokens via B2C Commerce&apos;s Account Manager.</description>
    <label>B2C CRM Sync AuthToken Settings</label>
    <pluralLabel>B2C CRM Sync AuthToken Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/B2C_CRM_Sync_Default_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>... represents the default configuration used to manage the configuration leveraged during production operation.</description>
    <label>B2C CRM Sync Default Configuration</label>
    <pluralLabel>B2C CRM Sync Default Configuration</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CRM_Sync_Default_Configuration__mdt/fields/Active_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Active_Configuration__c</fullName>
    <description>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</description>
    <inlineHelpText>... represents which B2C CRM Sync configuration setting profile should be used for production operation.</inlineHelpText>
    <label>Active Configuration</label>
    <referenceTo>B2C_CRMSync_Setting__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Default Configuration</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Default_Configuration</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/B2C_CRMSync_Setting__mdt.object-meta.xml
<CustomObject>
    <description>... global configuration settings for B2C CRM Sync; manages instances of configuration settings for the B2C Commerce integration package.</description>
    <label>B2C CRM Sync Configuration Settings</label>
    <pluralLabel>B2C CRM Sync Configuration Settings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Account_Contact_Model__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact_Model__c</fullName>
    <label>Account Contact Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Person</fullName>
                <default>true</default>
                <label>Person</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Account_Record_Type_Developername__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Type_Developername__c</fullName>
    <description>... represents the default recordType to use when creating a Parent Account for a given B2C Contact.</description>
    <inlineHelpText>... represents the default recordType to use when creating a Parent Account for a given B2C Contact.</inlineHelpText>
    <label>Account Record Type Developer Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/B2C_CRM_Sync_AuthToken_Settings__c.field-meta.xml
<CustomField>
    <fullName>B2C_CRM_Sync_AuthToken_Settings__c</fullName>
    <description>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</description>
    <inlineHelpText>... represents the authToken configuration settings that are mapped to a set of b2c-crm-sync configuration settings.</inlineHelpText>
    <label>B2C CRM Sync AuthToken Settings</label>
    <referenceTo>B2C_CRM_Sync_AuthToken_Settings__mdt</referenceTo>
    <relationshipLabel>B2C CRM Sync Configuration Settings</relationshipLabel>
    <relationshipName>B2C_CRM_Sync_Configuration_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Account_Name__c</fullName>
    <description>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Account if one was not provided or could not be calculated from the child Contact properties.</inlineHelpText>
    <label>Default Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Default_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact_Name__c</fullName>
    <description>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</description>
    <inlineHelpText>... represents the default name to use for a B2C Contact if one was not provided via the Contact&apos;s properties.</inlineHelpText>
    <label>Default Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_B2C_Process_Contact_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_B2C_Process_Contact_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</description>
    <inlineHelpText>... managed whether the B2C Process Contact trigger is enabled and used to process Contact Updates.</inlineHelpText>
    <label>Enable B2C Process Contact Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_B2C_Update_Counts_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_B2C_Update_Counts_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... managed whether the B2C Update Counts trigger is enabled and used to calculate site and customerList counts.</description>
    <inlineHelpText>... managed whether the B2C Update Counts trigger is enabled and used to calculate site and customerList counts.</inlineHelpText>
    <label>Enable B2C Update Counts Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CRMSync_Setting__mdt/fields/Enable_Client_ID_CertValidation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Client_ID_CertValidation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</description>
    <inlineHelpText>... this checkbox manages the behavior of the B2C Client ID certValidation trigger; when enabled -- it verifies that the JWT Certificate name maps to an existing Salesforce certificate.</inlineHelpText>
    <label>Enable Client ID CertValidation Trigger</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CConfigurationManager.cls
/**
 * @author Abraham David Lloyd
 * @date February 14th, 2021
 *
 * @description This class is used to retrieve the default configuration settings
 * for the B2C CRM Sync application.
 */
public with sharing class B2CConfigurationManager {

    /**
     * @description Helper function retrieves the associated Account Manager / JWT authentication
     * configuration settings that are related to the active configuration.
     * @return {Map<String, String>} Returns a map containing the related accountManager configuration settings
     */
    public static Map<String, String> getAccountManagerSettings() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Map<String, String> output;

        // Initialize the output map
        output = new Map<String, String>();

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c,
                        Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Port__c,
                        Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Token_Url__c,
                        Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Expiration_in_Minutes__c,
                        Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_Algorithm__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Set the output variable to contain the Account Manager configuration settings to leverage
        output.put('AccountManagerUrl', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Url__c);
        output.put('AccountManagerPort', String.valueOf(configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Port__c));
        output.put('AccountManagerSuffix', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Account_Manager_Token_Url__c);
        output.put('ExpirationInMinutes', String.valueOf(configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.Expiration_in_Minutes__c));
        output.put('JWTAlgorithm', configurationProfile.Active_Configuration__r.B2C_CRM_Sync_AuthToken_Settings__r.JWT_Algorithm__c);

        // Return the associated Account Manager configuration settings
        return output;

    }

    /**
     * @description Helper function retrieves the default businessAccount
     * developerName used for accounts / contacts.
     * @return {String} Returns the developerName for the B2c Business Account
     */
    public static String getAccountRecordTypeDeveloperName() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        String output;

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.Account_Record_Type_Developername__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Set the output variable to contain the specified configuration property
        output = configurationProfile.Active_Configuration__r.Account_Record_Type_Developername__c;

        // Return the configured account / recordType developerName
        return output;

    }

    /**
     * @description Helper function retrieves the default customerModel based on the
     * configuration profile that is configured.
     * @return {String} Returns the configured customerModel (Standard or Person).
     */
    public static String getDefaultAccountContactModel() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        String output;

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.Account_Contact_Model__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Set the output variable to contain the specified configuration property
        output = configurationProfile.Active_Configuration__r.Account_Contact_Model__c;

        // Return the configured customerModel
        return output;

    }

    /**
     * @description Helper function that returns the default Account / Contact names.
     * @return {Map<String, String>} Returns the names used to default the Account Name
     * and Contact lastName during the resolution and contact-creation process
     */
    public static Map<String, String> getDefaultAccountContactNames() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;
        Map<String, String> output;

        // Initialize the output map
        output = new Map<String, String>();

        // Get the default configuration profile
        configurationProfile = [
            SELECT  Active_Configuration__r.Default_Account_Name__c,
                    Active_Configuration__r.Default_Contact_Name__c
            FROM    B2C_CRM_Sync_Default_Configuration__mdt
            WHERE   DeveloperName = 'Production_Configuration'
            LIMIT   1
        ];

        // Capture and seed the default account / contact names
        output.put('accountName', configurationProfile.Active_Configuration__r.Default_Account_Name__c);
        output.put('contactName', configurationProfile.Active_Configuration__r.Default_Contact_Name__c);

        // Return the output property
        return output;

    }

    /**
     * @description Helper function that retrieves the current default configuration.
     * @return {Boolean} Returns the enabled / active status of the B2C Process Contact trigger
     */
    public static Boolean isB2CProcessContactTriggerEnabled() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.DeveloperName,
                        Active_Configuration__r.MasterLabel,
                        Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Return the enabled status of the B2C ProcessContact Trigger
        return configurationProfile.Active_Configuration__r.Enable_B2C_Process_Contact_Trigger__c;

    }

    /**
     * @description Helper function that retrieves the current default configuration.
     * @return {Boolean} Returns the enabled / active status of the B2C Update Counts trigger
     */
    public static Boolean isB2CUpdateCountsTriggerEnabled() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.DeveloperName,
                        Active_Configuration__r.MasterLabel,
                        Active_Configuration__r.Enable_B2C_Update_Counts_Trigger__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Return the enabled status of the B2C UpdateCounts Trigger
        return configurationProfile.Active_Configuration__r.Enable_B2C_Update_Counts_Trigger__c;

    }


    /**
     * @description Helper function that retrieves the current default configuration.
     * @return {Boolean} Returns the enabled / active status of the B2C ClientID CertValidation trigger
     */
    public static Boolean isB2CClientIDCertValidationTriggerEnabled() {

        // Initialize local variables
        B2C_CRM_Sync_Default_Configuration__mdt configurationProfile;

        // Get the default configuration profile
        configurationProfile = [
                SELECT  Active_Configuration__r.DeveloperName,
                        Active_Configuration__r.MasterLabel,
                        Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c
                FROM    B2C_CRM_Sync_Default_Configuration__mdt
                WHERE   DeveloperName = 'Production_Configuration'
                LIMIT   1
        ];

        // Return the enabled status of the B2C CLient ID certValidation trigger
        return configurationProfile.Active_Configuration__r.Enable_Client_ID_CertValidation_Trigger__c;

    }

}