src/sfdc/force-app/main/default/objects/Contact/fields/Last_Platform_Event_Applied_Updates__c.field-meta.xml
<CustomField>
    <fullName>Last_Platform_Event_Applied_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the last processed Platform Event applied updates to the Contact definition (checked = updates applied, unchecked = no updates applied).</description>
    <inlineHelpText>... describes if the last processed Platform Event applied updates to the Contact definition (checked = updates applied, unchecked = no updates applied).</inlineHelpText>
    <label>Last Platform Event Applied Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/Last_Platform_Event_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Platform_Event_Processed_Date__c</fullName>
    <description>... represents the date that the last B2C Commerce integration Process Contact platform event was processed.</description>
    <inlineHelpText>... represents the date that the last B2C Commerce integration Process Contact platform event was processed.</inlineHelpText>
    <label>Last Platform Event Processed Date</label>
    <type>DateTime</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/Last_Update_Pushed_to_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Last_Update_Pushed_to_B2C_Commerce__c</fullName>
    <description>... represents the date / time that an update of this Contact was pushed to its corresponding B2C Commerce profile.</description>
    <inlineHelpText>... represents the date / time that an update of this Contact was pushed to its corresponding B2C Commerce profile.</inlineHelpText>
    <label>Last Update Pushed to B2C Commerce</label>
    <type>DateTime</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/Total_Updates_to_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Total_Updates_to_B2C_Commerce__c</fullName>
    <defaultValue>0</defaultValue>
    <description>... represents the total number of profile updates pushed to B2C Commerce for a given Salesforce Contact.</description>
    <inlineHelpText>... represents the total number of profile updates pushed to B2C Commerce for a given Salesforce Contact.</inlineHelpText>
    <label>Total Updates to B2C Commerce</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CIAPublishCustomerProfile_Test.cls
/**
 * @author Eric Schultz
 * @date April 11th, 2021
 *
 * @description 
*/
@IsTest
private class B2CIAPublishCustomerProfile_Test {

    /**
     * @see B2CIAValidateContact.validateContact
     * @description
     */
    @IsTest
    static void isValid() {
        List<B2CIAPublishCustomerProfileInput> inputList = new List<B2CIAPublishCustomerProfileInput>();
        B2CIAPublishCustomerProfileInput input = new B2CIAPublishCustomerProfileInput();

        Contact c = new Contact(
            LastName = 'lastname',
            Total_Updates_to_B2C_Commerce__c = 0,
            Last_Update_Pushed_to_B2C_Commerce__c = System.Datetime.now(),
            Last_Platform_Event_Applied_Updates__c = false,
            Last_Platform_Event_Processed_Date__c = System.Datetime.now()
        );

        Database.insert( c );

        input.namedCredential = 'NamedCredential';
        input.apiVersion = 'apiVersion';
        input.b2cCustomerListId = 'id';
        input.b2cCustomerNo = 'customerno';
        input.b2cCustomerId = 'customerid';
        input.crmCustomerListId = 'crmCustomerListId';
        input.crmContactId = c.Id;
        input.crmContact = c;
        input.b2cProfileJSON = '{}';

        inputList.add( input );

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerListsSites'));
            B2CIAPublishCustomerProfile.publishCustomerProfile( inputList );
        Test.stopTest();
    }
}