src/sfdc/base/main/default/objects/B2C_Commerce_ProcessCustomerDetails__e/B2C_Commerce_ProcessCustomerDetails__e.object-meta.xml
<CustomObject>
    <description>... announces the event to process B2C Commerce Customer Profile details for a given Customer (either to retrieve updates from B2C Commerce or push updates to B2C Commerce).</description>
    <label>B2C Commerce: Process Customer Details</label>
    <pluralLabel>B2C Commerce: Process Customer Details</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Commerce_ProcessCustomerDetails__e/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the B2C Commerce Customer Profile&apos;s Customer Number (CustomerNo).</description>
    <label>B2C Customer No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Audit_OCAPI_API_Response__c.field-meta.xml
<CustomField>
    <fullName>Audit_OCAPI_API_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether the B2C Commerce OCAPI Interactions should be audited.</description>
    <inlineHelpText>... describes whether the B2C Commerce OCAPI Interactions should be audited.</inlineHelpText>
    <label>Audit B2C Commerce OCAPI Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/Contact/fields/Audit_OCAPI_API_Response__c.field-meta.xml
<CustomField>
    <fullName>Audit_OCAPI_API_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether the B2C Commerce OCAPI Response used to update this record should be audited.</description>
    <inlineHelpText>... describes whether the B2C Commerce OCAPI Response used to update this record should be audited.</inlineHelpText>
    <label>Audit B2C Commerce OCAPI Response</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/personaccounts/main/default/classes/B2CProcessPersonAccountHelper.cls
/**
 * @author Abraham David Lloyd
 * @date July 11th, 2021
 *
 * @description Abstracts the trigger logic into its own class.
 */
public with sharing class B2CProcessPersonAccountHelper {

    /**
     * @description Helper method to abstract the trigger processing into a separate class.  This class
     * compares Account updates -- and evaluates if a publishEvent needs to be triggered to B2C Commerce
     * for a given customerProfile.
     *
     * @param triggerNew {List<Account>} Represents the collection of new Account records to process
     * @param triggerOld {List<Account>} Represents the collection of old Account records to process
     */
    public static void processTrigger(List<Account> triggerNew, List<Account> triggerOld) {

        // Initialize local variables
        List<Account> newPersonAccounts;
        List<Account> oldPersonAccounts;
        Account newPersonAccount;
        Account oldPersonAccount;
        Contact validateContact;
        Contact publishContact;
        Map<String, B2C_Instance__c> instanceMap;
        Map<String, B2C_CustomerList__c> customerListMap;
        B2CIAValidateContactInput validateContactInput;
        B2CIAValidateContactResult validateContactResult;
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings;
        List<B2C_Integration_Field_Mappings__mdt> contactFieldMappings;
        List<B2C_Integration_Field_Mappings__mdt> updatedFieldMappings;
        List<B2C_Integration_Field_Mappings__mdt> publishFieldMappings;
        Map<String, Object> thisB2CProfile;
        String thisB2CProfileJSON;
        List<B2C_Commerce_ProcessCustomerDetails__e> peCollection;

        // Get the fieldMappings for the customerProfile object
        contactFieldMappings = B2CMetaFieldMappings.getFieldMappingsForPublishing('Contact');
        fieldMappings = B2CMetaFieldMappings.toggleAlternateObjectAttributes(contactFieldMappings);

        // Only process the trigger if publish-friendly fieldMappings are found
        if (fieldMappings.size() > 0) {

            // Initialize the instance maps
            instanceMap = new Map<String, B2C_Instance__c>();
            customerListMap = new Map<String, B2C_CustomerList__c>();

            // Initialize the platformEvent collection
            peCollection = new List<B2C_Commerce_ProcessCustomerDetails__e>();

            // Create collections representing new / old personAccount records
            newPersonAccounts = triggerNew;
            oldPersonAccounts = triggerOld;

            // Loop over the collection of personAccount updates
            for (Integer accountIndex = 0; accountIndex < newPersonAccounts.size(); accountIndex++) {

                // Create a reference to the current new / old PersonAccount being processed
                newPersonAccount = newPersonAccounts.get(accountIndex);
                oldPersonAccount = oldPersonAccounts.get(accountIndex);

                // Has the updated by B2C Platform Event been flipped?  If so, continue
                // Prevent a circular loop where the PE updates fire trigger updates
                if (newPersonAccount.Updated_by_B2C_Platform_Event__pc == true) {

                    // Remove the platform-event updated flag
                    newPersonAccount.Updated_by_B2C_Platform_Event__pc = false;

                    // Continue processing
                    continue;

                }

                // Is the Contact mapped to a CustomerList and have a valid customerNo?  If not, continue
                if (newPersonAccount.B2C_CustomerList__pc == null || newPersonAccount.B2C_Customer_No__pc == null) { continue; }

                // Maintain the customerList and instance maps to minimize queries
                instanceMap = B2CProcessContactHelper.updateInstanceMap(newPersonAccount.B2C_Instance__pc, instanceMap);
                customerListMap = B2CProcessContactHelper.updateCustomerListMap(newPersonAccount.B2C_CustomerList__pc, customerListMap);

                // Initialize the validateContact
                validateContact = new Contact();

                // Default the contact identifier
                validateContact.Id = newPersonAccount.PersonContactId;

                // Seed the integration control properties for the contact; this represents the
                // minimum collection of Contact attributes required to feed the PlatformEvent
                validateContact.B2C_Disable_Integration__c = newPersonAccount.B2C_Disable_Integration__pc;
                validateContact.Audit_OCAPI_API_Response__c = newPersonAccount.Audit_OCAPI_API_Response__pc;
                validateContact.B2C_Customer_No__c = newPersonAccount.B2C_Customer_No__pc;

                // Create an instance of the validateContactInput class and process validation
                validateContactInput = B2CProcessContactHelper.getValidateContactInput(validateContact,
                        instanceMap.get(newPersonAccount.B2C_Instance__pc),
                        customerListMap.get(newPersonAccount.B2C_CustomerList__pc));

                // Validate the contact results and determine if integration is enabled
                validateContactResult = B2CProcessContactHelper.getValidateContactResult(validateContactInput);

                // Is integration disabled for this contact? If so, then continue
                if (validateContactResult.allowIntegrationProcess == false) { continue; }

                // Determine if this Contact been updated through one of the publish fieldMappings
                updatedFieldMappings = B2CProcessContactHelper.getUpdatedFieldMappings(oldPersonAccount, newPersonAccount, fieldMappings);

                // Has the Contact record been updated?
                if (updatedFieldMappings.size() > 0) {

                    // Toggle the fieldMappings back to the Contact so we can use them for the publishEvent
                    publishFieldMappings = B2CMetaFieldMappings.toggleAlternateObjectAttributes(updatedFieldMappings);

                    // Generate a contact-representation of the Account that only includes publishable fields
                    publishContact = B2CAccountManager.getPublishContact(newPersonAccount, updatedFieldMappings);

                    // If so, get the field-specific updates for the updated contact
                    thisB2CProfile = B2CContactManager.getPublishProfile(publishContact, publishFieldMappings);
                    thisB2CProfileJSON = JSON.serializePretty(thisB2CProfile, true);

                    // Then create the Contact Publish Platform Event and override the publish JSON
                    peCollection.add(B2CProcessContactHelper.createPublishPlatformEvent(validateContactInput, thisB2CProfileJSON));

                }

            }

            // Publish the PE Collection if it contains at least one (1) record
            if (peCollection.size() > 0) { EventBus.publish(peCollection); }

        }

    }


}