src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_Attribute_Type__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_Attribute_Type__c</fullName>
    <inlineHelpText>The type of the attribute within B2C Commerce. This list only contains the available types within the Salesforce Platform.</inlineHelpText>
    <label>B2C Commerce Attribute Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>boolean</fullName>
                <default>true</default>
                <label>boolean</label>
            </value>
            <value>
                <fullName>string</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_OCAPI_Attribute__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_OCAPI_Attribute__c</fullName>
    <description>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</description>
    <inlineHelpText>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</inlineHelpText>
    <label>B2C Commerce OCAPI Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Consume_Updates_from_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Consume_Updates_from_B2C_Commerce__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, mapped Service Cloud attributes will consume updates from their B2C Commerce counter parts.</description>
    <inlineHelpText>... when checked, mapped Service Cloud attributes will consume updates from their B2C Commerce counter parts.</inlineHelpText>
    <label>Consume Updates from B2C Commerce</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Enable_for_Integration__c.field-meta.xml
<CustomField>
    <fullName>Enable_for_Integration__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, this field mapping will be processed during multi-cloud integration events between B2C Commerce and Service Clouds.  If un-checked, this field mapping will ignored during multi-cloud integration events.</description>
    <inlineHelpText>... when checked, this field mapping will be processed during multi-cloud integration events between B2C Commerce and Service Clouds.  If un-checked, this field mapping will ignored during multi-cloud integration events.</inlineHelpText>
    <label>Enable for Multi-Cloud Integration</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Description__c.field-meta.xml
<CustomField>
    <fullName>Field_Description__c</fullName>
    <description>... represents the customer-facing description for a given field.  This should only be used to describe fields for externalObjects, as Salesforce Object fields will carry their own field descriptions.</description>
    <inlineHelpText>... represents the customer-facing description for a given field.  This should only be used to describe fields for externalObjects, as Salesforce Object fields will carry their own field descriptions.</inlineHelpText>
    <label>Field Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</description>
    <inlineHelpText>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</inlineHelpText>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Position_in_UI__c.field-meta.xml
<CustomField>
    <fullName>Position_in_UI__c</fullName>
    <defaultValue>25</defaultValue>
    <description>... represents the position of the field in the forms within the Salesforce Core Platform UI</description>
    <inlineHelpText>... represents the position of the field in the forms within the Salesforce Core Platform UI</inlineHelpText>
    <label>Position in UI</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Push_Updates_to_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Push_Updates_to_B2C_Commerce__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, updates made to mapped Service Cloud Contact attributes are pushed to their B2C Commerce attribute counterparts.</description>
    <inlineHelpText>... when checked, updates made to mapped Service Cloud Contact attributes are pushed to their B2C Commerce attribute counterparts.</inlineHelpText>
    <label>Push Updates to B2C Commerce</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Seed_Property_on_First_Time_Sync__c.field-meta.xml
<CustomField>
    <fullName>Seed_Property_on_First_Time_Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if this property should be synchronized on the first-time sync between B2C Commerce and Service Cloud.  If checked, each identified property will be synchronized regardless of all other synchronization settings.  Consider this an initial one-time override over the other synchronization methods.</description>
    <inlineHelpText>... describes if this property should be synchronized on the first-time sync between B2C Commerce and Service Cloud.  If checked, each identified property will be synchronized regardless of all other synchronization settings.</inlineHelpText>
    <label>Seed Property on First-Time Sync</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute_Alt__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute_Alt__c</fullName>
    <description>... represents an alternate Salesforce Object field name that can be used to map this attribute to a B2C Commerce object.</description>
    <inlineHelpText>... represents an alternate Salesforce Object field name that can be used to map this attribute to a B2C Commerce object.</inlineHelpText>
    <label>Salesforce Platform Attribute Alternate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Object__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Object__c</fullName>
    <description>... represents the Service Cloud object whose attributes are being mapped to B2C Commerce customer fields.</description>
    <inlineHelpText>... represents the Service Cloud object whose attributes are being mapped to B2C Commerce customer fields.</inlineHelpText>
    <label>Service Cloud Object</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Show_in_UI__c.field-meta.xml
<CustomField>
    <fullName>Show_in_UI__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, show the field in the Salesfore Core platform UI for view/edit purpose.</description>
    <inlineHelpText>... when checked, show the field in the Salesfore Core platform UI for view/edit purpose.</inlineHelpText>
    <label>Show in UI</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CMetaFieldMappings.cls
/**
 * @author Abraham David Lloyd
 * @date May 10th, 2020
 *
 * @description This class is used to manage the field-mappings for Salesforce
 * objects being integrated as part of the B2C tool-kit.  The class accesses
 * field-mappings via customer meta-data describing the B2C Commerce object
 * properties that map back to Salesforce object properties.
*/
//noinspection LongLine
public with sharing class B2CMetaFieldMappings extends B2CBaseMeta {

    /**
     * @description This method is used toggle the Salesforce Platform Attributes -- flipping from
     * respecting the standard attribute to the alternate attribute.  The alternate attribute describes
     * an alternate field relationship related to the primary one.
     *
     * @param fieldMappingsToToggle {List<B2C_Integration_Field_Mappings__mdt>} Represents the collection
     * of fieldMappings to toggle
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> toggleAlternateObjectAttributes(
        List<B2C_Integration_Field_Mappings__mdt> fieldMappingsToToggle
    ) {

        // Initialize local Variables
        List<B2C_Integration_Field_Mappings__mdt> output;
        String salesforceObjectAttribute;
        String salesforceObjectAttributeAlt;

        // Default the output collection
        output = new List<B2C_Integration_Field_Mappings__mdt>();

        // Loop over the collection of field mappings, and toggle the independent elements
        for (B2C_Integration_Field_Mappings__mdt thisFieldMapping : fieldMappingsToToggle) {

            // Create a reference to the alternate and standard fields
            salesforceObjectAttribute = thisFieldMapping.Service_Cloud_Attribute__c;
            salesforceObjectAttributeAlt = thisFieldMapping.Service_Cloud_Attribute_Alt__c;

            // Only toggle when an alternate mapping is defined
            if (salesforceObjectAttributeAlt != null) {

                // Toggle the Salesforce Platform fieldMappings
                thisFieldMapping.Service_Cloud_Attribute__c = salesforceObjectAttributeAlt;
                thisFieldMapping.Service_Cloud_Attribute_Alt__c = salesforceObjectAttribute;

            }

            // Add the mapping to the output collection
            output.add(thisFieldMapping);

        }

        // Return the output variable
        return output;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * active field mappings for a given Salesforce object.
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose field-mappings are defined
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappings(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_FIELDMAPPINGOBJECTNOTFOUND, objectType);

        if (
            // Verify that we can access these fields
            B2C_Integration_Field_Mappings__mdt.SObjectType.getDescribe().isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Service_Cloud_Object__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Service_Cloud_Attribute__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Service_Cloud_Attribute_Alt__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.B2C_Commerce_OCAPI_Attribute__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Seed_Property_on_First_Time_Sync__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Push_Updates_to_B2C_Commerce__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Consume_Updates_from_B2C_Commerce__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Enable_for_Integration__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Field_Label__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Field_Description__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Service_Cloud_Object__c.isAccessible() &&
            Schema.SObjectType.B2C_Integration_Field_Mappings__mdt.fields.Enable_for_Integration__c.isAccessible()
        ) {

            // Retrieve the collection of field-mappings related to this object
            outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        Service_Cloud_Attribute_Alt__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c,
                        Field_Label__c,
                        Field_Description__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                AND     Enable_for_Integration__c = TRUE
            ];

            // Were any records returned by this query?
            testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        }

        // Return the field-mapping values
        return outputFieldMappings;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * active field mappings for a given Salesforce object that support API retrieval.
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose
     * field-mappings are being retrieved
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappingsForRetrieval(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_FIELDMAPPINGOBJECTNOTFOUND, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        Service_Cloud_Attribute_Alt__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        B2C_Commerce_Attribute_Type__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c,
                        Field_Label__c,
                        Field_Description__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                        AND Enable_for_Integration__c = TRUE
                        AND Consume_Updates_from_B2C_Commerce__c = TRUE
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * active field mappings for a given Salesforce object that should be rendered in the custom UI.
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose
     * field-mappings are being retrieved
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappingsForUIRendering(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_FIELDMAPPINGOBJECTNOTFOUND, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        Service_Cloud_Attribute_Alt__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        B2C_Commerce_Attribute_Type__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c,
                        Field_Label__c,
                        Field_Description__c,
                        Position_in_UI__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                        AND Enable_for_Integration__c = TRUE
                        AND Show_in_UI__c = TRUE
                ORDER BY Position_in_UI__c ASC
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * publishable field mappings for a given Salesforce object (ie -- these fields
     * can be published to B2C Commerce
     *
     * @param objectType {String} Represents the name / type of the Salesforce object
     * whose field-mappings are being retrieved
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappingsForPublishing(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_FIELDMAPPINGOBJECTNOTFOUND, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        Service_Cloud_Attribute_Alt__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        B2C_Commerce_Attribute_Type__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c,
                        Field_Label__c,
                        Field_Description__c,
                        Position_in_UI__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                        AND Enable_for_Integration__c = TRUE
                        AND Push_Updates_to_B2C_Commerce__c = TRUE
                ORDER BY Position_in_UI__c ASC
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;
    }

    /**
     * @description Retrieve the configured field mappings from the given {data}
     *
     * @param customerId {String}  The customer Id
     * @param data {JSONParse} The data retrieved from the B2C Commerce API
     * @param fieldMappings {List<B2C_Integration_Field_Mappings__mdt>} The collection of fieldMappings to process
     *
     * @return {Map<String, Object>} The list of found fields
     */
    public static Map<String, Object> mapFields(String customerId, JSONParse data, List<B2C_Integration_Field_Mappings__mdt> fieldMappings) {
        Map<String, Object> mappedObject = new Map<String, Object>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            try {
                if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'boolean') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getBooleanValue());
                } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'integer') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getIntegerValue());
                } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'number') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getDecimalValue());
                } else { // By default treat as a string
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getStringValue());
                }
            } catch (JSONParse.MissingKeyException e) {
                // Log the error but don't abort
                // This probably fires only because the value is not set on the address in the B2C Commerce
                // instance for this address, but the attribute still exists
                System.debug(
                    System.LoggingLevel.ERROR,
                    '--> B2C Exception: The attribute {' + fieldMapping.B2C_Commerce_OCAPI_Attribute__c + '} ' +
                    'has not been found in the given object {' + data.toStringPretty() + '} ' +
                    ' for the customer {' + customerId + '}.'
                );
            }
        }

        mappedObject.put('key', EncodingUtil.ConvertTohex(Crypto.GenerateAESKey(128)));

        return mappedObject;
    }
}