src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_OCAPI_Attribute__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_OCAPI_Attribute__c</fullName>
    <description>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</description>
    <inlineHelpText>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</inlineHelpText>
    <label>B2C Commerce OCAPI Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Consume_Updates_from_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Consume_Updates_from_B2C_Commerce__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, mapped Service Cloud attributes will consume updates from their B2C Commerce counter parts.</description>
    <inlineHelpText>... when checked, mapped Service Cloud attributes will consume updates from their B2C Commerce counter parts.</inlineHelpText>
    <label>Consume Updates from B2C Commerce</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Enable_for_Integration__c.field-meta.xml
<CustomField>
    <fullName>Enable_for_Integration__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, this field mapping will be processed during multi-cloud integration events between B2C Commerce and Service Clouds.  If un-checked, this field mapping will ignored during multi-cloud integration events.</description>
    <inlineHelpText>... when checked, this field mapping will be processed during multi-cloud integration events between B2C Commerce and Service Clouds.  If un-checked, this field mapping will ignored during multi-cloud integration events.</inlineHelpText>
    <label>Enable for Multi-Cloud Integration</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Push_Updates_to_B2C_Commerce__c.field-meta.xml
<CustomField>
    <fullName>Push_Updates_to_B2C_Commerce__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... when checked, updates made to mapped Service Cloud Contact attributes are pushed to their B2C Commerce attribute counterparts.</description>
    <inlineHelpText>... when checked, updates made to mapped Service Cloud Contact attributes are pushed to their B2C Commerce attribute counterparts.</inlineHelpText>
    <label>Push Updates to B2C Commerce</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Seed_Property_on_First_Time_Sync__c.field-meta.xml
<CustomField>
    <fullName>Seed_Property_on_First_Time_Sync__c</fullName>
    <defaultValue>true</defaultValue>
    <description>... describes if this property should be synchronized on the first-time sync between B2C Commerce and Service Cloud.  If checked, each identified property will be synchronized regardless of all other synchronization settings.  Consider this an initial one-time override over the other synchronization methods.</description>
    <inlineHelpText>... describes if this property should be synchronized on the first-time sync between B2C Commerce and Service Cloud.  If checked, each identified property will be synchronized regardless of all other synchronization settings.</inlineHelpText>
    <label>Seed Property on First-Time Sync</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Object__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Object__c</fullName>
    <description>... represents the Service Cloud object whose attributes are being mapped to B2C Commerce customer fields.</description>
    <inlineHelpText>... represents the Service Cloud object whose attributes are being mapped to B2C Commerce customer fields.</inlineHelpText>
    <label>Service Cloud Object</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CMetaFieldMappings.cls
/**
 * @author Abraham David Lloyd
 * @date May 10th, 2020
 *
 * @description This class is used to manage the field-mappings for Salesforce
 * objects being integrated as part of the B2C tool-kit.  The class accesses
 * field-mappings via customer meta-data describing the B2C Commerce object
 * properties that map back to Salesforce object properties.
*/
public with sharing class B2CMetaFieldMappings extends B2CBaseMeta {

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * active field mappings for a given Salesforce object.
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose field-mappings are defined
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappings(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_FieldMappingObjectNotFound, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
            SELECT  Service_Cloud_Object__c,
                    Service_Cloud_Attribute__c,
                    B2C_Commerce_OCAPI_Attribute__c,
                    Seed_Property_on_First_Time_Sync__c,
                    Push_Updates_to_B2C_Commerce__c,
                    Consume_Updates_from_B2C_Commerce__c,
                    Enable_for_Integration__c
            FROM    B2C_Integration_Field_Mappings__mdt
            WHERE   Service_Cloud_Object__c = :objectType
                    AND Enable_for_Integration__c = TRUE
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * active field mappings for a given Salesforce object that support API retrieval.
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose field-mappings are being retrieved
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappingsForRetrieval(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_FieldMappingObjectNotFound, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                        AND Enable_for_Integration__c = TRUE
                        AND Consume_Updates_from_B2C_Commerce__c = TRUE
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;

    }

    /**
     * @description This method is used to retrieve the collection of multi-cloud
     * publishable field mappings for a given Salesforce object (ie -- these fields
     * can be published to B2C Commerce
     *
     * @param objectType {String} Represents the name / type of the Salesforce object whose field-mappings are being retrieved
     * @return List<B2C_Integration_Field_Mappings__mdt> Returns a collection of field mappings
     */
    public static List<B2C_Integration_Field_Mappings__mdt> getFieldMappingsForPublishing(String objectType) {

        // Initialize local variables
        List<B2C_Integration_Field_Mappings__mdt> outputFieldMappings;
        String errorMsg;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_FieldMappingObjectNotFound, objectType);

        // Retrieve the collection of field-mappings related to this object
        outputFieldMappings = [
                SELECT  Service_Cloud_Object__c,
                        Service_Cloud_Attribute__c,
                        B2C_Commerce_OCAPI_Attribute__c,
                        Seed_Property_on_First_Time_Sync__c,
                        Push_Updates_to_B2C_Commerce__c,
                        Consume_Updates_from_B2C_Commerce__c,
                        Enable_for_Integration__c
                FROM    B2C_Integration_Field_Mappings__mdt
                WHERE   Service_Cloud_Object__c = :objectType
                        AND Enable_for_Integration__c = TRUE
                        AND Push_Updates_to_B2C_Commerce__c = TRUE
        ];

        // Were any records returned by this query?
        testForEmptyRecordSet(outputFieldMappings.size(), errorMsg);

        // Return the field-mapping values
        return outputFieldMappings;

    }

}