src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute_Alt__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute_Alt__c</fullName>
    <description>... represents an alternate Salesforce Object field name that can be used to map this attribute to a B2C Commerce object.</description>
    <inlineHelpText>... represents an alternate Salesforce Object field name that can be used to map this attribute to a B2C Commerce object.</inlineHelpText>
    <label>Salesforce Platform Attribute Alternate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/Audit_OCAPI_API_Response__c.field-meta.xml
<CustomField>
    <fullName>Audit_OCAPI_API_Response__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether the B2C Commerce OCAPI Response used to update this record should be audited.</description>
    <inlineHelpText>... describes whether the B2C Commerce OCAPI Response used to update this record should be audited.</inlineHelpText>
    <label>Audit B2C Commerce OCAPI Response</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Disable_Integration__c.field-meta.xml
<CustomField>
    <fullName>B2C_Disable_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</description>
    <inlineHelpText>... describes if integration between B2C Commerce and Service Cloud is disabled for a given Contact.</inlineHelpText>
    <label>B2C Disable Integration</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/person-accounts/main/default/classes/B2CAccountManager.cls
/**
 * @author Abraham David Lloyd
 * @date April 11th, 2021
 *
 * @description This class is used to interact with PersonAccounts and convert them
 * to Contact representations we can use to leverage common b2c-crm-sync business logic.
 */
public with sharing class B2CAccountManager extends B2CBaseMeta {

    /**
     * @description Helper function that takes the identified collection of modified fields for an
     * Account (scoped by fieldMappings), and creates a Contact reflecting these field-values.
     *
     * @param personAccountToProcess {Account} Represents the PersonAccount being processed
     * @param updatedFieldMappings {List<B2C_Integration_Field_Mappings__mdt>} Represents the fieldMappings identifying updated fields
     * @return {Contact} Returns a Contact containing only the updated fields that were identified
     */
    public static Contact getPublishContact(Account personAccountToProcess, List<B2C_Integration_Field_Mappings__mdt> updatedFieldMappings) {

        // Initialize local variables
        Contact output;

        // Create the new contact instance
        output = new Contact();

        // Default the Id for the current Contact
        output.Id = personAccountToProcess.PersonContactId;
        output.AccountId = personAccountToProcess.Id;

        // Include the integration control fields
        output.B2C_Disable_Integration__c = personAccountToProcess.B2C_Disable_Integration__pc;
        output.Audit_OCAPI_API_Response__c = personAccountToProcess.Audit_OCAPI_API_Response__pc;

        // Loop over the field-mappings and attribute the updated / changed values
        for (B2C_Integration_Field_Mappings__mdt thisFieldMapping : updatedFieldMappings) {

            // Seed the contact with each modified property of the Account
            output.put(
                thisFieldMapping.Service_Cloud_Attribute_Alt__c,
                personAccountToProcess.get(thisFieldMapping.Service_Cloud_Attribute__c)
            );

        }

        // Return the publish Contact-representation
        return output;

    }

}