src/sfdc/base/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</description>
    <inlineHelpText>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Base_API_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_API_Url__c</fullName>
    <description>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</description>
    <formula>LEFT(API_Url__c, FIND( &apos;/s/&apos;, API_Url__c)-1)</formula>
    <inlineHelpText>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</inlineHelpText>
    <label>Base API Url</label>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</description>
    <inlineHelpText>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</inlineHelpText>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CActiveCustomerPromotions.cls
public with sharing class B2CActiveCustomerPromotions {
    public static final String METADATA_NAME = 'B2C_Promotion__x';
    public static final Integer MAXIMUM_COUPON_CODES = 10;

    /**
     * Retrieves the label of the promotion fields
     *
     * @return List<Map<String, String>> The map of Id<>Label of the promotion fields
     */
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getPromotionsLabels() {
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings = B2CMetaFieldMappings.getFieldMappingsForUIRendering(METADATA_NAME);
        List<Map<String, String>> fields = new List<Map<String, String>>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            Map<String, String> field = new Map<String, String>();
            field.put('id', fieldMapping.Service_Cloud_Attribute__c);
            field.put('label', fieldMapping.Field_Label__c);
            fields.add(field);
        }

        return fields;
    }

    /**
     * Issue a coupon for the given promotion
     *
     * @return String The coupon code issued
     */
    @AuraEnabled
    public static List<String> getCouponCodes(String recordId, String couponId, String siteId, Integer maximumCouponCodes) {
        List<String> couponCodes =  new List<String>();
        if (String.isEmpty(recordId) || string.isEmpty(couponId) || String.isEmpty(siteId)) {
            return couponCodes;
        }

        // Get the contact that matches the given customer Id
        // If no contact is found, an error is thrown
        Contact contact = B2CContactManager.getContactByCustomerId(recordId);
        maximumCouponCodes = maximumCouponCodes != null ? maximumCouponCodes : MAXIMUM_COUPON_CODES;

        HttpRequest req = B2CHttpRequestHelper.getCouponCodesRequest(
            contact.B2C_CustomerList__r.Base_API_Url__c,
            B2CAuthTokenHelper.getB2CAuthTokenByClientIDValue(contact.B2C_CustomerList__r.B2C_Client_ID__c, true),
            contact.B2C_CustomerList__r.OCAPI_Version_No__c,
            siteId,
            couponId,
            maximumCouponCodes
        );

        Http https = new Http();
        HttpResponse res = https.send(req);
        Integer statusCode = res.getStatusCode();
        if (statusCode != 200) {
            return couponCodes;
        }

        JSONParse responseParsedJSON = new JSONParse(res.getBody());
        Integer count = responseParsedJSON.get('count').getIntegerValue();
        if (count > 0) {
            List<JSONParse> couponCodesData = responseParsedJSON.get('data').asList();
            for (JSONParse couponCodeData : couponCodesData) {
                String couponCode = couponCodeData.get('code').getStringValue();
                Boolean issued = false;
                try {
                    issued = couponCodeData.get('issued').getBooleanValue();
                } catch (Exception e) {
                    // No issued property on the coupon code, which happens the coupon code has not been issued yet
                    System.debug('The coupon is not yet issued, so the property is not sent by the OCAPI');
                }

                if (!issued) {
                    couponCodes.add(couponCode);
                }
            }
        }

        return couponCodes;
    }
}