src/sfdc/base/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerAddress__x/B2C_CustomerAddress__x.object-meta.xml
<CustomObject>
    <description>B2C_CustomerAddress</description>
    <externalDataSource>B2C_Customer_Address_Book</externalDataSource>
    <externalName>B2C_CustomerAddress</externalName>
    <label>B2C Customer Address</label>
    <pluralLabel>B2C Customer Addresses</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</description>
    <inlineHelpText>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Base_API_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_API_Url__c</fullName>
    <description>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</description>
    <formula>LEFT(API_Url__c, FIND( &apos;/s/&apos;, API_Url__c)-1)</formula>
    <inlineHelpText>... represents the base API Url derived from the CustomerList&apos;s Record API Url.</inlineHelpText>
    <label>Base API Url</label>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Enable_Address_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Enable_Address_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Address Book addresses can be published from the Salesforce Platform to a B2C Commerce instance.</description>
    <inlineHelpText>... describes whether B2C Commerce Address Book addresses can be published from the Salesforce Platform to a B2C Commerce instance.</inlineHelpText>
    <label>Enable Address Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/Enable_Address_Retrieval__c.field-meta.xml
<CustomField>
    <fullName>Enable_Address_Retrieval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if Customer Profile Addresses can be retrieved from B2C Commerce.</description>
    <inlineHelpText>... describes if Customer Profile Addresses can be retrieved from B2C Commerce.</inlineHelpText>
    <label>Enable Address Retrieval</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_OCAPI_Attribute__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_OCAPI_Attribute__c</fullName>
    <description>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</description>
    <inlineHelpText>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</inlineHelpText>
    <label>B2C Commerce OCAPI Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</description>
    <inlineHelpText>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</inlineHelpText>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CCustomerAddressBook.cls
public with sharing class B2CCustomerAddressBook {
    public static final String METADATA_NAME = 'B2C_CustomerAddress__x';

    /**
     * Retrieves the label of the address fields
     *
     * @return List<Map<String, String>> The map of Id<>Label of the address fields
     */
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getCustomerAddressLabels() {
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings = B2CMetaFieldMappings.getFieldMappingsForUIRendering(METADATA_NAME);
        List<Map<String, String>> fields = new List<Map<String, String>>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            Map<String, String> field = new Map<String, String>();
            field.put('id', fieldMapping.Service_Cloud_Attribute__c);
            field.put('label', fieldMapping.Field_Label__c);
            fields.add(field);
        }

        return fields;
    }

    /**
     * Retrieves the label of the address fields
     *
     * @return List<Map<String, String>> The map of Id<>Label of the address fields
     */
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getCustomerAddressFormFields() {
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings = B2CMetaFieldMappings.getFieldMappingsForPublishing(METADATA_NAME);
        List<Map<String, String>> fields = new List<Map<String, String>>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            Map<String, String> field = new Map<String, String>();
            field.put('id', fieldMapping.Service_Cloud_Attribute__c);
            field.put('label', fieldMapping.Field_Label__c);
            fields.add(field);
        }

        return fields;
    }

    /**
     * Fetches the customer's address book from B2C Commerce and returns it
     *
     * @param {String} customerId The customer Id for whom to fetch the addresses
     *
     * @return List<Map<String, Object>> The list of addresses found
     */
    @AuraEnabled(cacheable=false)
    public static List<Map<String, Object>> getCustomerAddresses(String recordId) {
        List<Map<String, Object>> addresses =  new List<Map<String, Object>>();
        if (String.isEmpty(recordId)) {
            return addresses;
        }

        // Get the contact that matches the given customer Id
        // If no contact is found, an error is thrown
        Contact contact = B2CContactManager.getContactByCustomerId(recordId);
        // In case the customer list disallow address retrieval, return an empty address list
        if (!contact.B2C_CustomerList__r.Enable_Address_Retrieval__c) {
            return addresses;
        }

        HttpRequest req = B2CHttpRequestHelper.getCustomerProfileAddressesRequest(
            contact.B2C_CustomerList__r.Base_API_Url__c,
            B2CAuthTokenHelper.getB2CAuthTokenByClientIDValue(contact.B2C_CustomerList__r.B2C_Client_ID__c, true),
            contact.B2C_CustomerList__r.OCAPI_Version_No__c,
            contact.B2C_CustomerList__r.Name,
            contact.B2C_Customer_No__c
        );

        Http https = new Http();
        HttpResponse res = https.send(req);
        Integer statusCode = res.getStatusCode();
        if (statusCode != 200) {
            return addresses;
        }

        JSONParse responseParsedJSON = new JSONParse(res.getBody());
        Integer count = responseParsedJSON.get('count').getIntegerValue();
        if (count > 0) {
            List<JSONParse> addressesData = responseParsedJSON.get('data').asList();
            for (JSONParse addressData : addressesData) {
                addresses.add(B2CMetaFieldMappings.mapFields(recordId, addressData, B2CMetaFieldMappings.getFieldMappingsForUIRendering(METADATA_NAME)));
            }
        }

        return addresses;
    }

    /**
     * Fetches the customer's address from B2C Commerce and returns it
     *
     * @param {String} customerId The customer Id for whom to fetch the address
     * @param {String} addressId The address Id of the address to fetch
     *
     * @return Map<String, Object>
     */
    @AuraEnabled(cacheable=false)
    public static Map<String, Object> getCustomerAddressById(String customerId, String addressId) {
        Map<String, Object> address =  new Map<String, Object>();
        if (String.isEmpty(customerId) || String.isEmpty(addressId)) {
            return address;
        }

        // Get the contact that matches the given customer Id
        // If no contact is found, an error is thrown
        Contact contact = B2CContactManager.getContactByCustomerId(customerId);
        // In case the customer list disallow address retrieval, return an empty address
        if (!contact.B2C_CustomerList__r.Enable_Address_Retrieval__c) {
            return address;
        }

        HttpRequest req = B2CHttpRequestHelper.getCustomerProfileAddressRequest(
            contact.B2C_CustomerList__r.Base_API_Url__c,
            B2CAuthTokenHelper.getB2CAuthTokenByClientIDValue(contact.B2C_CustomerList__r.B2C_Client_ID__c, true),
            contact.B2C_CustomerList__r.OCAPI_Version_No__c,
            contact.B2C_CustomerList__r.Name,
            contact.B2C_Customer_No__c,
            addressId
        );

        Http https = new Http();
        HttpResponse res = https.send(req);
        Integer statusCode = res.getStatusCode();
        if (statusCode != 200) {
            return address;
        }

        JSONParse responseParsedJSON = new JSONParse(res.getBody());
        return B2CMetaFieldMappings.mapFields(customerId, responseParsedJSON, B2CMetaFieldMappings.getFieldMappingsForPublishing(METADATA_NAME));
    }

    /**
     * Patches the customer's address to B2C Commerce
     *
     * @param {String} customerId The customer Id for whom to fetch the address
     * @param {String} addressId The address Id of the address to patch
     * @param {String} address The address details
     *
     * @return String Any error in case something went wrong
     */
    @AuraEnabled(cacheable=true)
    public static String patchCustomerAddress(String customerId, String addressId, Map<String, Object> address) {
        if (String.isEmpty(customerId) || String.isEmpty(addressId)) {
            return B2CConstant.buildErrorMessage(B2CConstant.ERRORS_B2CCOMMERCE_ADDRESSBOOK_FAILED_TO_PATCH_ADDRESS, 'Wrong parameters sent in the method');
        }

        // Get the contact that matches the given customer Id
        // If no contact is found, an error is thrown
        Contact contact = B2CContactManager.getContactByCustomerId(customerId);
        // In case the customer list disallow address publishing, return an empty address
        if (!contact.B2C_CustomerList__r.Enable_Address_Publishing__c) {
            return B2CConstant.buildErrorMessage(B2CConstant.ERRORS_B2CCOMMERCE_ADDRESSBOOK_FAILED_TO_PATCH_ADDRESS, 'Customer list disallows address updates');
        }

        // Build the address object to send to the B2C Commerce instance, based on the field mappings
        Map<String, Object> addressData = new Map<String, Object>();
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings = B2CMetaFieldMappings.getFieldMappingsForPublishing(METADATA_NAME);
        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            addressData.put(
                fieldMapping.B2C_Commerce_OCAPI_Attribute__c,
                address.get(fieldMapping.Service_Cloud_Attribute__c)
            );
        }

        HttpRequest req = B2CHttpRequestHelper.getCustomerProfileAddressPatchRequest(
            contact.B2C_CustomerList__r.Base_API_Url__c,
            B2CAuthTokenHelper.getB2CAuthTokenByClientIDValue(contact.B2C_CustomerList__r.B2C_Client_ID__c, true),
            contact.B2C_CustomerList__r.OCAPI_Version_No__c,
            contact.B2C_CustomerList__r.Name,
            contact.B2C_Customer_No__c,
            addressId,
            JSON.serialize(addressData, true)
        );

        Http https = new Http();
        HttpResponse res = https.send(req);
        if (res.getStatusCode() != 200) {
            JSONParse responseParsedJSON = new JSONParse(res.getBody());
            return B2CConstant.buildErrorMessage(B2CConstant.ERRORS_B2CCOMMERCE_ADDRESSBOOK_FAILED_TO_PATCH_ADDRESS, responseParsedJSON.get('fault').get('message').getStringValue());
        }

        return null;
    }
}