src/sfdc/base/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/Audit_Authentication_API_Interactions__c.field-meta.xml
<CustomField>
    <fullName>Audit_Authentication_API_Interactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</description>
    <inlineHelpText>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</inlineHelpText>
    <label>Audit Authentication API Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID_Label__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID_Label__c</fullName>
    <description>... represents the customer-facing label / name for the B2C Client ID.</description>
    <inlineHelpText>... represents the customer-facing label / name for the B2C Client ID.</inlineHelpText>
    <label>B2C Client ID Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</description>
    <inlineHelpText>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce identifier used to represent a customerList.</description>
    <inlineHelpText>... represents the B2C Commerce identifier used to represent a customerList.</inlineHelpText>
    <label>CustomerList ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C CustomerList.</description>
    <formula>B2C_Client_ID__r.JWT_Certificate_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C CustomerList.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</description>
    <inlineHelpText>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C Instances</relationshipLabel>
    <relationshipName>B2C_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C Instance.</description>
    <formula>B2C_Client_ID__r.JWT_Certificate_Name__c</formula>
    <inlineHelpText>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C Instance.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_ID__c</fullName>
    <description>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</description>
    <inlineHelpText>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</inlineHelpText>
    <label>B2C Customer ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</description>
    <inlineHelpText>... represents the B2C Commerce storefront customer list that is associated to a given Contact.</inlineHelpText>
    <label>B2C CustomerList ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/classes/B2CProcessContact_EvalContactArg_Test.cls
/**
 * @author Abraham David Lloyd
 * @date July 4th, 2021
 *
 * @description This class is to validate that the B2CProcessContact's Evaluate
 * ContactArgument subFlow.
 */
@IsTest
private class B2CProcessContact_EvalContactArg_Test {

    /**
     * @description This method is used to create the base test-data that will be leveraged
     * by the unit-tests for the B2CCommerce_Process_Contact_HelperServiceEntry flow.
     */
    @IsTest
    static void prepareTestData() {

        // Initialize the clientId to use during testing
        B2C_Client_ID__c clientId = (B2C_Client_ID__c)TestDataFactory.createSObject('B2C_Client_ID__c', new Map<String,Object>{
            'Name' => 'my-test-clientId',
            'B2C_Client_ID_Label__c' => 'My Test ClientID',
            'JWT_Certificate_Name__c' => B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME,
            'Is_Active__c' => true,
            'Audit_Authentication_API_Interactions__c' => true
        });

        // Initialize the test instance
        B2C_Instance__c instance = (B2C_Instance__c)TestDataFactory.createSObject('B2C_Instance__c', new Map<String,Object>{
            'Name' => 'testInstance',
            'API_Url__c' => 'https://test.com',
            'B2C_Client_ID__c' => clientId.Id,
            'Is_Active__c' => true
        });

        // Initialize the test customerList
        B2C_CustomerList__c customerList = (B2C_CustomerList__c)TestDataFactory.createSObject('B2C_CustomerList__c', new Map<String,Object>{
            'Name' => 'RefArch',
            'B2C_Instance__c' => instance.Id,
            'B2C_Client_ID__c' => clientId.Id,
            'CustomerList_ID__c' => 'RefArch',
            'API_Url__c' => 'https://test.com',
            'OCAPI_Version_No__c' => 'v20_10'
        });

        // Validate that all of the test-data is created
        System.assert(customerList != null, 'Expected a customerList to be created');
        System.assert(clientId != null, 'Expected an clientId to be created');
        System.assert(instance != null, 'Expected an instance to be created');

    }

    /**
     * @description This test attempts to resolve a Contact profile that does not exist with
     * a valid B2C CustomerList.  It should return no error with a valid successFlag, a recognized
     * B2C CustomerList, and no errors.
     */
    @IsTest
    static void testSourceContactB2CCustomerListValidSuccess() {

        // Seed the testData
        prepareTestData();

        // Initialize local Variables
        Map<String, Object> flowArguments;
        Flow.Interview evalContactArgumentFlow;

        // Initialize the testContact record
        Contact sourceContact = new Contact(
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'test-user@b2csa.qa.salesforce.com',
            B2C_Customer_ID__c = 'bcdKh1ixccNKau8lFXjFMaTEoj',
            B2C_CustomerList_ID__c = 'RefArch',
            B2C_Customer_No__c = '00013505'
        );

        // Initialize the flow outputVariables
        List<String> errorMessage;
        Boolean hasError;
        Boolean hasIdentifiers;
        Boolean isSuccess;
        Boolean isVerified;
        Account parentAccount;
        B2C_CustomerList__c parentB2CCustomerList;
        Contact flowSourceContact;
        Contact verifiedContact;

        // Initialize the flow arguments
        flowArguments = new Map<String, Object>();
        flowArguments.put('sourceContact', sourceContact);

        // Execute the filterMap flow attempt to resolve the specific contact identified
        evalContactArgumentFlow = Flow.Interview.createInterview('B2CCommerce_Process_Contact_EvaluateContactArgument', flowArguments);

        Test.startTest();

            // Initialize the flow and start it
            evalContactArgumentFlow.start();

            // Retrieve the output arguments
            errorMessage = (List<String>) evalContactArgumentFlow.getVariableValue('ErrorMessage');
            hasError = (Boolean) evalContactArgumentFlow.getVariableValue('hasError');
            hasIdentifiers = (Boolean) evalContactArgumentFlow.getVariableValue('hasIdentifiers');
            isSuccess = (Boolean) evalContactArgumentFlow.getVariableValue('isSuccess');
            isVerified = (Boolean) evalContactArgumentFlow.getVariableValue('isVerified');
            parentAccount = (Account) evalContactArgumentFlow.getVariableValue('parentAccount');
            parentB2CCustomerList = (B2C_CustomerList__c) evalContactArgumentFlow.getVariableValue('parentB2CCustomerList');
            flowSourceContact = (Contact) evalContactArgumentFlow.getVariableValue('sourceContact');
            verifiedContact = (Contact) evalContactArgumentFlow.getVariableValue('verifiedContact');

        Test.stopTest();

        // Verify that the resolutionAttempt was successful
        System.assertEquals(true, isSuccess, 'Expected the isSuccess flag to be set to true');
        System.assertEquals(false, hasError, 'Expected the hasError flag to be false');
        System.assertEquals(null, parentAccount, 'Expected no parentAccount to be returned');
        System.assert(parentB2CCustomerList != null, 'Expected a valid B2C CustomerList to be returned');
        System.assert(flowSourceContact != null, 'Expected a valid sourceContact to be provided with the flowResults');

    }

    /**
     * @description This test attempts to resolve a Contact profile that does not exist with
     * an in-valid B2C CustomerList.  It should return an error with no parentCustomerList
     * identified.
     */
    @IsTest
    static void testSourceContactB2CCustomerListInValidFailure() {

        // Seed the testData
        prepareTestData();

        // Initialize local Variables
        Map<String, Object> flowArguments;
        Flow.Interview evalContactArgumentFlow;

        // Initialize the testContact record
        Contact sourceContact = new Contact(
            FirstName = 'Anonymous',
            LastName = 'Customer',
            Email = 'test-user@b2csa.qa.salesforce.com',
            B2C_Customer_ID__c = 'bcdKh1ixccNKau8lFXjFMaTEoj',
            B2C_CustomerList_ID__c = 'Unknown',
            B2C_Customer_No__c = '00013505'
        );

        // Initialize the flow outputVariables
        List<String> errorMessage;
        Boolean hasError;
        Boolean hasIdentifiers;
        Boolean isSuccess;
        Boolean isVerified;
        Account parentAccount;
        B2C_CustomerList__c parentB2CCustomerList;
        Contact flowSourceContact;
        Contact verifiedContact;

        // Initialize the flow arguments
        flowArguments = new Map<String, Object>();
        flowArguments.put('sourceContact', sourceContact);

        // Execute the filterMap flow attempt to resolve the specific contact identified
        evalContactArgumentFlow = Flow.Interview.createInterview('B2CCommerce_Process_Contact_EvaluateContactArgument', flowArguments);

        Test.startTest();

            // Initialize the flow and start it
            evalContactArgumentFlow.start();

            // Retrieve the output arguments
            errorMessage = (List<String>) evalContactArgumentFlow.getVariableValue('ErrorMessage');
            hasError = (Boolean) evalContactArgumentFlow.getVariableValue('hasError');
            hasIdentifiers = (Boolean) evalContactArgumentFlow.getVariableValue('hasIdentifiers');
            isSuccess = (Boolean) evalContactArgumentFlow.getVariableValue('isSuccess');
            isVerified = (Boolean) evalContactArgumentFlow.getVariableValue('isVerified');
            parentAccount = (Account) evalContactArgumentFlow.getVariableValue('parentAccount');
            parentB2CCustomerList = (B2C_CustomerList__c) evalContactArgumentFlow.getVariableValue('parentB2CCustomerList');
            flowSourceContact = (Contact) evalContactArgumentFlow.getVariableValue('sourceContact');
            verifiedContact = (Contact) evalContactArgumentFlow.getVariableValue('verifiedContact');

        Test.stopTest();

        // Verify that the resolutionAttempt was successful
        System.assertEquals(false, isSuccess, 'Expected the isSuccess flag to be set to false');
        System.assertEquals(true, hasError, 'Expected the hasError flag to be true');
        System.assert(ErrorMessage.size() > 0, 'Expected at least one (1) error to be returned by this flow');
        System.assertEquals(null, parentAccount, 'Expected no parentAccount to be returned');
        System.assertEquals(null, parentB2CCustomerList, 'Expected no parent B2C CustomerList to be returned');
        System.assert(flowSourceContact != null, 'Expected a valid sourceContact to be provided with the flowResults');

    }

    /**
     * @description This test attempts to resolve a Contact profile that exists by
     * the B2C CustomerID value. It expects to resolve a Contact using the B2C Customer ID.
     */
    @IsTest
    static void testResolveByB2CCustomerIDSuccess() {

        // Seed the testData
        prepareTestData();

        // Retrieve the test customerList
        B2C_CustomerList__c testCustomerList = [
            SELECT  Id,
                    Name
            FROM    B2C_CustomerList__c
            LIMIT   1
        ];

        // Initialize the testContact record
        Account testAccount = (Account) TestDataFactory.createSObject('Account', new Map<String,Object>{
            'Name' => 'Registered Customer',
            'RecordTypeId' => B2CIACustomerResolution_TestHelper.getRecordType(B2CConfigurationManager.getAccountRecordTypeDeveloperName()).Id
        });

        // Initialize the testContact record with the AccountId
        Contact myTestContact = (Contact) TestDataFactory.createSObject('Contact', new Map<String,Object>{
            'FirstName' => 'Anonymous',
            'LastName' => 'Customer',
            'Email' => 'test-user@b2csa.qa.salesforce.com',
            'AccountId' => testAccount.Id,
            'B2C_CustomerList__c' => testCustomerList.Id,
            'B2C_CustomerList_ID__c' => testCustomerList.Name,
            'B2C_Customer_ID__c' => 'test-customerid',
            'B2C_Customer_No__c' => 'test-customerno'
        });

        // Initialize local Variables
        Map<String, Object> flowArguments;
        Flow.Interview evalContactArgumentFlow;

        // Initialize the testContact record
        Contact sourceContact = new Contact(
            B2C_Customer_ID__c = 'test-customerid'
        );

        // Initialize the flow outputVariables
        List<String> errorMessage;
        Boolean hasError;
        Boolean hasIdentifiers;
        Boolean isSuccess;
        Boolean isVerified;
        Account parentAccount;
        B2C_CustomerList__c parentB2CCustomerList;
        Contact flowSourceContact;
        Contact verifiedContact;

        // Initialize the flow arguments
        flowArguments = new Map<String, Object>();
        flowArguments.put('sourceContact', sourceContact);

        // Execute the filterMap flow attempt to resolve the specific contact identified
        evalContactArgumentFlow = Flow.Interview.createInterview('B2CCommerce_Process_Contact_EvaluateContactArgument', flowArguments);

        Test.startTest();

            // Initialize the flow and start it
            evalContactArgumentFlow.start();

            // Retrieve the output arguments
            errorMessage = (List<String>) evalContactArgumentFlow.getVariableValue('ErrorMessage');
            hasError = (Boolean) evalContactArgumentFlow.getVariableValue('hasError');
            hasIdentifiers = (Boolean) evalContactArgumentFlow.getVariableValue('hasIdentifiers');
            isSuccess = (Boolean) evalContactArgumentFlow.getVariableValue('isSuccess');
            isVerified = (Boolean) evalContactArgumentFlow.getVariableValue('isVerified');
            parentAccount = (Account) evalContactArgumentFlow.getVariableValue('parentAccount');
            parentB2CCustomerList = (B2C_CustomerList__c) evalContactArgumentFlow.getVariableValue('parentB2CCustomerList');
            flowSourceContact = (Contact) evalContactArgumentFlow.getVariableValue('sourceContact');
            verifiedContact = (Contact) evalContactArgumentFlow.getVariableValue('verifiedContact');

        Test.stopTest();

        // Verify that the resolutionAttempt was successful
        System.assertEquals(true, isSuccess, 'Expected the isSuccess flag to be set to true');
        System.assertEquals(false, hasError, 'Expected the hasError flag to be false');
        System.assertEquals(null, parentAccount, 'Did not expect a parentAccount to be returned');
        System.assertEquals(null, parentB2CCustomerList, 'DId not expected a parent B2C CustomerList to be returned');
        System.assert(flowSourceContact != null, 'Expected a valid sourceContact to be provided with the flowResults');

    }

}