src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the default B2C Client ID used to perform REST API interactions with this CustomerList.</description>
    <inlineHelpText>... represents the default B2C Client ID used to perform REST API interactions with this CustomerList.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/B2C_Integration_Field_Mappings__mdt.object-meta.xml
<CustomObject>
    <description>... describes the B2C Commerce system objects and custom fields that map / correspond to Service Cloud objects and attributes.  Used to define multi-cloud field mappings and integration behavior.</description>
    <label>B2C Integration Field Mapping</label>
    <pluralLabel>B2C Integration Field Mappings</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_Attribute_Type__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_Attribute_Type__c</fullName>
    <inlineHelpText>The type of the attribute within B2C Commerce. This list only contains the available types within the Salesforce Core platform.</inlineHelpText>
    <label>B2C Commerce Attribute Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>boolean</fullName>
                <default>true</default>
                <label>boolean</label>
            </value>
            <value>
                <fullName>string</fullName>
            </value>
            <value>
                <fullName>integer</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/B2C_Commerce_OCAPI_Attribute__c.field-meta.xml
<CustomField>
    <fullName>B2C_Commerce_OCAPI_Attribute__c</fullName>
    <description>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</description>
    <inlineHelpText>... represents the B2C Commerce OCAPI response attribute mapped to the Service Cloud attribute.</inlineHelpText>
    <label>B2C Commerce OCAPI Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Description__c.field-meta.xml
<CustomField>
    <fullName>Field_Description__c</fullName>
    <description>... represents the customer-facing description for a given field.  This should only be used to describe fields for externalObjects, as Salesforce Object fields will carry their own field descriptions.</description>
    <inlineHelpText>... represents the customer-facing description for a given field.  This should only be used to describe fields for externalObjects, as Salesforce Object fields will carry their own field descriptions.</inlineHelpText>
    <label>Field Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</description>
    <inlineHelpText>... represents the customer-facing label to be used by a given field.  This field should only be used for externalObject mappings -- as the Salesforce Object fields carry their own label.</inlineHelpText>
    <label>Field Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Integration_Field_Mappings__mdt/fields/Service_Cloud_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Service_Cloud_Attribute__c</fullName>
    <description>... represents the Service Cloud attribute mapped to the specified object.</description>
    <inlineHelpText>... represents the Service Cloud attribute mapped to the specified object.</inlineHelpText>
    <label>Service Cloud Attribute</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_ID__c</fullName>
    <description>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</description>
    <inlineHelpText>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</inlineHelpText>
    <label>B2C Customer ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_No__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_No__c</fullName>
    <description>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the external / customer-facing B2C Commerce customer profile number associated to a given Contact.</inlineHelpText>
    <label>B2C Customer No</label>
    <length>250</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CDataSourceHelper.cls
/**
 * @author Jordane Bachelet
 * @date June 29th, 2021
 *
 * @description This class is a helper class used to create B2C Data Sources on the.
 * Salesforce Platform that can be leveraged by Salesforce Connect.
 */
public with sharing class B2CDataSourceHelper {
    /**
     * @description This method creates the Schema of External Object based on configured mapping fields and return the table schema for the External Object generation
     *
     * @param tableName {String}
     * @param tableLabelSingular {String}
     * @param tableLabelPlural {String}
     * @param tableDescription {String}
     * @param indirectLookupColumn {String}
     * @param indirectLookupColumnLabel {String}
     * @param indirectLookupColumnDescription {String}
     * @param indirectLookupTargetObject {String}
     * @param indirectLookupTargetField {String}
     * @param fieldMappings List<B2C_Integration_Field_Mappings__mdt>
     * @return {List<DataSource.Table>} tables
     * */
    public static List<DataSource.Table> generateSyncTables(
        String tableName,
        String tableLabelSingular,
        String tableLabelPlural,
        String tableDescription,
        String indirectLookupColumn,
        String indirectLookupColumnLabel,
        String indirectLookupColumnDescription,
        String indirectLookupTargetObject,
        String indirectLookupTargetField,
        List<B2C_Integration_Field_Mappings__mdt> fieldMappings) {
        List<DataSource.Table> tables = new List<DataSource.Table>();
        // Get the fieldMappings for the customer address object and add them to the columns list
        List<DataSource.Column> columns = B2CDataSourceHelper.generateColumns(fieldMappings);

        // Create the indirect look-up column governing the address-book relationships
        DataSource.Column indirectColumn = DataSource.Column.indirectLookup(indirectLookupColumn, indirectLookupTargetObject, indirectLookupTargetField);
        indirectColumn.label = indirectLookupColumnLabel;
        indirectColumn.description = indirectLookupColumnDescription;

        // Always apply the following columns:
        // - ExternalId -> Required by Salesforce Connect as unique identifier in the Core Platform
        // - Display URL -> Required by Salesforce Connect to be able to open the detail page within the external system
        // - indirectLookupColumn -> The indirect lookup to the "Parent" record
        columns.add(DataSource.Column.text('ExternalId', 255));
        columns.add(DataSource.Column.url('DisplayUrl'));
        columns.add(indirectColumn);

        tables.add(
            DataSource.Table.get(
                tableName,
                tableLabelSingular,
                tableLabelPlural,
                tableDescription,
                'ExternalId',
                columns
            )
        );

        return tables;
    }

    /**
     * @description Generate the columns for a table from the given field mappings
     *
     * @param fieldMappings {List<B2C_Integration_Field_Mappings__mdt>}  The field mappings to use to generate the columns
     * @return {List<DataSource.Column>}
     */
    public static List<DataSource.Column> generateColumns(List<B2C_Integration_Field_Mappings__mdt> fieldMappings) {
        List<DataSource.Column> columns = new List<DataSource.Column>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            DataSource.Column column = new DataSource.Column();

            if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'boolean') {
                column = DataSource.Column.boolean(fieldMapping.Service_Cloud_Attribute__c);
            } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'integer') {
                column = DataSource.Column.integer(fieldMapping.Service_Cloud_Attribute__c, 10);
            } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'number') {
                column = DataSource.Column.number(fieldMapping.Service_Cloud_Attribute__c, 10, 2);
            } else { // By default treat as a string
                column = DataSource.Column.text(fieldMapping.Service_Cloud_Attribute__c, 255);
            }

            column.label = fieldMapping.Field_Label__c;
            column.description = fieldMapping.Field_Description__c;
            columns.add(column);
        }

        return columns;
    }

    /**
     * @description Retrieve the configured field mappings from the given {data}
     *
     * @param customerId {String}  The customer Id
     * @param data {JSONParse} The data retrieved from the B2C Commerce API
     * @param fieldMappings {List<B2C_Integration_Field_Mappings__mdt>} The collection of fieldMappings to process
     * @return {Map<String, Object>} The list of found fields
     */
    public static Map<String, Object> mapFields(String customerId, JSONParse data, List<B2C_Integration_Field_Mappings__mdt> fieldMappings) {
        Map<String, Object> mappedObject = new Map<String, Object>();

        for (B2C_Integration_Field_Mappings__mdt fieldMapping : fieldMappings) {
            try {
                if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'boolean') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getBooleanValue());
                } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'integer') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getIntegerValue());
                } else if (fieldMapping.B2C_Commerce_Attribute_Type__c == 'number') {
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getDecimalValue());
                } else { // By default treat as a string
                    mappedObject.put(fieldMapping.Service_Cloud_Attribute__c, data.get(fieldMapping.B2C_Commerce_OCAPI_Attribute__c).getStringValue());
                }
            } catch (JSONParse.MissingKeyException e) {
                // Log the error but don't abort
                // This probably fires only because the value is not set on the address in the B2C Commerce instance for this address, but the attribute still exists
                System.debug(
                    'The attribute {' + fieldMapping.B2C_Commerce_OCAPI_Attribute__c + '} ' +
                    'has not been found in the given object {' + data.toStringPretty() + '} ' +
                    ' for the customer {' + customerId + '}.'
                );
            }
        }

        return mappedObject;
    }

    /**
     * @description Get the contact that matches the given {customerId}
     * If multiple records are found, the query limits to the first one
     *
     * @param customerId {String} The customer Id to use to find the contact
     * @return {Contact} The found contact or null if none is found
     */
    public static Contact getContactByCustomerId(String customerId) {
        String errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_ContactNotFound, customerId);
        Query contactQuery = new Query('Contact');
        contactQuery.selectField('AccountId');
        contactQuery.selectField('B2C_Customer_Id__c');
        contactQuery.selectField('B2C_Customer_No__c');
        contactQuery.selectField('B2C_CustomerList__r.Name');
        contactQuery.selectField('B2C_CustomerList__r.API_Url__c');
        contactQuery.selectField('B2C_CustomerList__r.B2C_Client_ID__c');
        contactQuery.selectField('B2C_CustomerList__r.OCAPI_Version_No__c');
        contactQuery.setLimit(1);
        contactQuery.addConditionEq('B2C_Customer_ID__c', customerId);
        contactQuery.addConditionEq('Id', customerId);
        contactQuery.addConditionEq('AccountId', customerId);
        contactQuery.switchToDisjunction();

        List<Contact> contacts = contactQuery.run();

        return (Contact)B2CBaseMeta.processReturnResult('Contact', false, contacts, errorMsg);
    }
}