src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Audit_Authentication_API_Interactions__c.field-meta.xml
<CustomField>
    <fullName>Audit_Authentication_API_Interactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</description>
    <inlineHelpText>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</inlineHelpText>
    <label>Audit Authentication API Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID_Label__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID_Label__c</fullName>
    <description>... represents the customer-facing label / name for the B2C Client ID.</description>
    <inlineHelpText>... represents the customer-facing label / name for the B2C Client ID.</inlineHelpText>
    <label>B2C Client ID Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CIARequestB2CAuthToken_Test.cls
/**
 * @author Abraham David Lloyd
 * @date June 29th, 2021
 *
 * @description This class exercises the successful and failed retrieval of the B2C AuthToken
 * via the B2C Commerce Account Manager leveraging JWT token-exchange.
 */
@IsTest
private class B2CIARequestB2CAuthToken_Test {

    /**
     * @see B2CIARequestB2CAuthToken.getB2CAuthTokenViaJWT
     * @description This test is used to exercise the retrieval of a B2C AuthToken's success scenario.
     * It validates that a successful token-retrieval is successfully processed.
     */
    @IsTest
    static void testIsSuccess() {

        // Initialize local variables
        B2C_Client_ID__c testClientID = new B2C_Client_ID__c(
            Name = 'my-test-clientId',
            B2C_Client_ID_Label__c = 'My Test ClientID',
            JWT_Certificate_Name__c = B2CConstant.CertTest_Validate_TestCertificateName,
            Is_Active__c = true,
            Audit_Authentication_API_Interactions__c = true
        );

        // Save the testClientID
        Database.insert(testClientID);

        // Initialize the result collection
        List<B2CIARequestB2CAuthTokenResult> tokenResultList = new List<B2CIARequestB2CAuthTokenResult>();

        Test.startTest();

            // Set the mock-generator for the current request (modeling success)
            Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('AccessTokenSuccess'));

            // Initialize the input argument collection
            B2CIARequestB2CAuthTokenInput req = new B2CIARequestB2CAuthTokenInput();

            // Seed the input arguments
            req.b2cClientIdRecordId = testClientID.Id;
            req.b2cClientId = testClientID.Name;
            req.jwtCertificate = testClientID.JWT_Certificate_Name__c;
            req.auditAuthenticationAPIInteractions = testClientID.Audit_Authentication_API_Interactions__c;
            req.bypassAuthTokenAuditing = false;

            // Request the authToken and validate the results
            tokenResultList = B2CIARequestB2CAuthToken.getB2CAuthTokenViaJWT(
                new List<B2CIARequestB2CAuthTokenInput>{
                    req
                }
            );

        Test.stopTest();

        // Validate that the request processed successfully
        System.assertEquals(tokenResultList.size() > 0, true, 'Expected a result to be processed and returned in the results');
        System.assertEquals(tokenResultList.get(0).statusCode, 200, 'Expected a successful http statusCode to be returned as part of this request');
        System.assertEquals(tokenResultList.get(0).accessToken, B2CConstant.AuthTest_AuthToken, 'Expected the accessToken to equal the test tokenValue.');

    }

    /**
     * @see B2CIARequestB2CAuthToken.getB2CAuthTokenViaJWT
     * @description This test is used to exercise the retrieval of a B2C AuthToken's failure scenario.
     * It validates that a token-retrieval failure is successfully processed.
     */
    @IsTest
    static void testIsFailure() {

        // Initialize local variables
        B2C_Client_ID__c testClientID = new B2C_Client_ID__c(
            Name = 'my-test-clientId',
            B2C_Client_ID_Label__c = 'My Test ClientID',
            JWT_Certificate_Name__c = B2CConstant.CertTest_Validate_TestCertificateName,
            Is_Active__c = true,
            Audit_Authentication_API_Interactions__c = true
        );

        // Save the testClientID
        Database.insert(testClientID);

        // Initialize the result collection
        List<B2CIARequestB2CAuthTokenResult> tokenResultList = new List<B2CIARequestB2CAuthTokenResult>();

        Test.startTest();

            // Set the mock-generator for the current request (modeling failure)
            Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('AccessTokenFailure'));

            // Initialize the input argument collection
            B2CIARequestB2CAuthTokenInput req = new B2CIARequestB2CAuthTokenInput();

            // Seed the input arguments
            req.b2cClientIdRecordId = testClientID.Id;
            req.b2cClientId = testClientID.Name;
            req.jwtCertificate = testClientID.JWT_Certificate_Name__c;
            req.auditAuthenticationAPIInteractions = testClientID.Audit_Authentication_API_Interactions__c;
            req.bypassAuthTokenAuditing = false;

            // Request the authToken and validate the results
            tokenResultList = B2CIARequestB2CAuthToken.getB2CAuthTokenViaJWT(
                new List<B2CIARequestB2CAuthTokenInput>{
                    req
                }
            );

        Test.stopTest();

        // Validate that the request processed successfully
        System.assertEquals(tokenResultList.size() > 0, true, 'Expected a result to be processed and returned in the results');
        System.assertEquals(tokenResultList.get(0).statusCode, 401, 'Expected a failure http statusCode to be returned as part of this request');

    }

}