src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CIAB2CClientIDCertValidator_Test.cls
/**
 * @author Abraham David Lloyd
 * @date June 10th, 2021
 *
 * @description This class is to validate that the IA used to exercise certificate
 * validation is able to successfully do so.
 */
@IsTest
private class B2CIAB2CClientIDCertValidator_Test {

    /**
     * @description Setup method that creates the customerList record(s) required to support testing.
     */
    @TestSetup static void setup() {

        // Setup a single clientId we can use for testing / validation
        B2C_Client_ID__c B2CClientID = (B2C_Client_ID__c) TestDataFactory.createSObject('B2C_Client_ID__c', new Map<String, Object>{
            'Name' => 'abcd1234',
            'JWT_Certificate_Name__c' => 'myCertificateName',
            'Is_Active__c' => true
        });

    }

    @IsTest
    static void validateCertificateTest() {

        // Initialize local variables
        List<B2CIAB2CClientIDCertValidatorInput> validatorInputs;
        List<B2CIAB2CClientIDCertValidatorResult> validationResults;
        B2CIAB2CClientIDCertValidatorInput validatorInput;

        // Initialize the input
        validatorInputs = new List<B2CIAB2CClientIDCertValidatorInput>();
        validatorInput = new B2CIAB2CClientIDCertValidatorInput();

        // Seed the clientId to work with
        validatorInput.B2CClientID = [
            SELECT  Id,
                    Name,
                    JWT_Certificate_Name__c,
                    Is_Active__c
            FROM    B2C_Client_ID__c
            LIMIT   1
        ];

        // Add the input to the processing collection
        validatorInputs.add(validatorInput);

        Test.startTest();

            // Attempt to exercise the certValidator and confirm that the certificate does / does not exist
            validationResults = B2CIAB2CClientIDCertValidator.validateCertificate(validatorInputs);

        Test.stopTest();

        // Loop over the collection of validation results and confirm the results
        for (B2CIAB2CClientIDCertValidatorResult validationResult : validationResults) {

            // We expect the certificate validation to fail because we cannot upload / create a self-signed certificate programmatically
            System.assertEquals(validationResult.isCertificateValid, false, 'Expected the certificate validation to fail.');

        }

    }

}