src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Audit_Authentication_API_Interactions__c.field-meta.xml
<CustomField>
    <fullName>Audit_Authentication_API_Interactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</description>
    <inlineHelpText>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</inlineHelpText>
    <label>Audit Authentication API Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID_Label__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID_Label__c</fullName>
    <description>... represents the customer-facing label / name for the B2C Client ID.</description>
    <inlineHelpText>... represents the customer-facing label / name for the B2C Client ID.</inlineHelpText>
    <label>B2C Client ID Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/Is_Certificate_Verified__c.field-meta.xml
<CustomField>
    <fullName>Is_Certificate_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the referenced certificate could be validated / verified.  Only B2C Client IDs with valid certificates can be used to request AuthTokens from the B2C Commerce Account Manager.</description>
    <inlineHelpText>... describes if the referenced certificate could be validated / verified.  Only B2C Client IDs with valid certificates can be used to request AuthTokens from the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Certificate Verified</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CAUthTokenHelper_Test.cls
/**
 * @author Abraham David Lloyd
 * @date June 28th, 2021
 *
 * @description This class is used to validate that we can call the getAuthToken flow via Apex
 * and leverage it internally within classes to retrieve authTokens from Account Manager.
 */
@IsTest
private class B2CAUthTokenHelper_Test {

    /**
     * @see B2CAuthTokenHelper.getB2CAuthToken
     * @description This test exercises the helper-method wrapper for the flow used to
     * retrieve an accessToken from the configured B2C Commerce AccountManager.  The test
     * successfully retrieves an authToken but does not persist it.
     */
    @IsTest
    static void testGetB2CAuthTokenWithoutAuditingSuccess() {

        // Initialize local variables
        Map<String, Object> authTokenResults;
        B2C_Client_ID__c definedClientID;

        // Initialize the test B2C ClientID
        B2C_Client_ID__c testClientID = new B2C_Client_ID__c(
            Name = 'my-test-clientId',
            B2C_Client_ID_Label__c = 'My Test ClientID',
            JWT_Certificate_Name__c = B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME,
            Is_Active__c = true,
            Audit_Authentication_API_Interactions__c = true
        );

        // Save the testClientID
        Database.insert(testClientID);

        // Retrieve the full-details for the testClientID
        definedClientID = [
            SELECT  Id,
                    Name,
                    B2C_Client_ID_Label__c,
                    JWT_Certificate_Name__c,
                    Is_Active__c,
                    Is_Certificate_Verified__c,
                    Audit_Authentication_API_Interactions__c,
                    IsDeleted
            FROM    B2C_Client_ID__c
            WHERE   Id = :testClientID.Id
        ];

        Test.startTest();

            // Set the mock-generator for the current request (modeling success)
            Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('AccessTokenSuccess'));

            // Attempt to retrieve a B2C AuthToken via the flow-wrapper
            authTokenResults = B2CAuthTokenHelper.getB2CAuthToken(definedClientID, true);

        Test.stopTest();

        // Validate that the request processed successfully
        System.assertEquals(authTokenResults.get('B2CAuthToken'), B2CConstant.AUTHTEST_AUTHTOKEN, 'Expected the authToken to match the default / test authToken constant');
        System.assertEquals(authTokenResults.get('IsSuccess'), true, 'Expected a success response of true for the authToken request');

    }

    /**
     * @see B2CAuthTokenHelper.getB2CAuthToken
     * @description This test exercises the helper-method wrapper for the flow used to
     * retrieve an accessToken from the configured B2C Commerce AccountManager.  The test
     * fails at retrieve an authToken.
     */
    @IsTest
    static void testGetB2CAuthTokenWithoutAuditingFailure() {

        // Initialize local variables
        Map<String, Object> authTokenResults;
        B2C_Client_ID__c definedClientID;

        // Initialize the test B2C ClientID
        B2C_Client_ID__c testClientID = new B2C_Client_ID__c(
                Name = 'my-test-clientId',
                B2C_Client_ID_Label__c = 'My Test ClientID',
                JWT_Certificate_Name__c = B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME,
                Is_Active__c = true,
                Audit_Authentication_API_Interactions__c = true
        );

        // Save the testClientID
        Database.insert(testClientID);

        // Retrieve the full-details for the testClientID
        definedClientID = [
                SELECT  Id,
                        Name,
                        B2C_Client_ID_Label__c,
                        JWT_Certificate_Name__c,
                        Is_Active__c,
                        Is_Certificate_Verified__c,
                        Audit_Authentication_API_Interactions__c,
                        IsDeleted
                FROM    B2C_Client_ID__c
                WHERE   Id = :testClientID.Id
        ];

        Test.startTest();

            // Set the mock-generator for the current request (modeling success)
            Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('AccessTokenFailure'));

            // Attempt to retrieve a B2C AuthToken via the flow-wrapper
            authTokenResults = B2CAuthTokenHelper.getB2CAuthToken(definedClientID, true);

        Test.stopTest();

        // Validate that the request processed successfully
        System.assertEquals(authTokenResults.get('B2CAuthToken'), null, 'Did not expected an authToken to be seeded as an error was caught');
        System.assertEquals(authTokenResults.get('IsSuccess'), false, 'Expected a failed success response as an error was caught');

    }

}