src/sfdc/force-app/main/default/objects/B2C_AuthToken__c/B2C_AuthToken__c.object-meta.xml
<CustomObject>
    <description>... represents the B2C AuthTokens used to enable REST API access associated with NamedCredentials and B2C ClientIDs.</description>
    <label>B2C AuthToken</label>
    <nameField>
        <label>B2C AuthToken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C AuthTokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_AuthToken__c/fields/B2C_AuthToken__c.field-meta.xml
<CustomField>
    <fullName>B2C_AuthToken__c</fullName>
    <description>... represents the AuthToken provided by the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the AuthToken provided by the B2C Commerce Account Manager.</inlineHelpText>
    <label>B2C AuthToken</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_AuthToken__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</description>
    <inlineHelpText>... represents the B2C ClientID used to generate a B2C Commerce / Account Manager AuthToken.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/B2C_Client_ID__c.object-meta.xml
<CustomObject>
    <description>... represents the collection of B2C Client IDs that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API calls.</description>
    <label>B2C Client ID</label>
    <nameField>
        <label>B2C Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Client IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Audit_Authentication_API_Interactions__c.field-meta.xml
<CustomField>
    <fullName>Audit_Authentication_API_Interactions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</description>
    <inlineHelpText>... when checked -- all B2C Commerce Account Manager authentication interactions are audited.</inlineHelpText>
    <label>Audit Authentication API Interactions</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the unique identifier that can be used to authenticate against the B2C Commerce Account Manager and leverage in OCAPI REST API call-outs.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Client_ID__c/fields/B2C_Client_ID_Label__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID_Label__c</fullName>
    <description>... represents the customer-facing label / name for the B2C Client ID.</description>
    <inlineHelpText>... represents the customer-facing label / name for the B2C Client ID.</inlineHelpText>
    <label>B2C Client ID Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</description>
    <inlineHelpText>... when checked -- this B2C Client ID can be used authenticate against the B2C Commerce Account Manager.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Client_ID__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerAddress__x/B2C_CustomerAddress__x.object-meta.xml
<CustomObject>
    <description>B2C_CustomerAddress</description>
    <externalDataSource>B2C_Customer_Address_Book</externalDataSource>
    <externalName>B2C_CustomerAddress</externalName>
    <label>B2C Customer Address</label>
    <pluralLabel>B2C Customer Addresses</pluralLabel>
</CustomObject>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/B2C_CustomerList__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce Customer Lists.</description>
    <label>B2C CustomerList</label>
    <nameField>
        <label>B2C CustomerList ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C CustomerLists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_CustomerList__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</description>
    <inlineHelpText>... represents the API Url used to retrieve the details for a given B2C Commerce CustomerList.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <description>... represents the default B2C Client ID used to perform REST API interactions with this CustomerList.</description>
    <inlineHelpText>... represents the default B2C Client ID used to perform REST API interactions with this CustomerList.</inlineHelpText>
    <label>B2C Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the B2C Commerce instance associated to a given CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce instance associated to a given CustomerList.</inlineHelpText>
    <label>B2C Instance</label>
    <referenceTo>B2C_Instance__c</referenceTo>
    <relationshipLabel>B2C CustomerLists</relationshipLabel>
    <relationshipName>B2C_CustomerLists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce identifier used to represent a customerList.</description>
    <inlineHelpText>... represents the B2C Commerce identifier used to represent a customerList.</inlineHelpText>
    <label>CustomerList ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if the existing B2C Commerce CustomerList is active and available for integration.</description>
    <inlineHelpText>... describes if the existing B2C Commerce CustomerList is active and available for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_CustomerList__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C CustomerList.</description>
    <formula>B2C_Client_ID__r.JWT_Certificate_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>... represents the JWT Certificate Name associated to the default B2C Client ID for a given B2C CustomerList.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/B2C_Instance__c.object-meta.xml
<CustomObject>
    <description>... represents an environment instance of B2C Commerce (ex. a sandbox, a realm, etc).</description>
    <label>B2C Instance</label>
    <nameField>
        <label>B2C Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</description>
    <inlineHelpText>... represents the base OCAPI Data REST API url for the B2C Commerce Instance.</inlineHelpText>
    <label>API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/fields/B2C_Client_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Client_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</description>
    <inlineHelpText>... represents the B2C ClientID that serves as the default for a given B2C Instance, its CustomerLists, and Sites.</inlineHelpText>
    <label>B2C Client ID</label>
    <referenceTo>B2C_Client_ID__c</referenceTo>
    <relationshipLabel>B2C Instances</relationshipLabel>
    <relationshipName>B2C_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if this B2C Commerce instance is active and enabled for integration.</description>
    <inlineHelpText>... describes if this B2C Commerce instance is active and enabled for integration.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Instance__c/fields/JWT_Certificate_Name__c.field-meta.xml
<CustomField>
    <fullName>JWT_Certificate_Name__c</fullName>
    <description>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</description>
    <inlineHelpText>... represents the Certificate that will be used to mint JWT tokens that can be exchanged for REST API AuthTokens via the B2C Commerce Account Manager.</inlineHelpText>
    <label>JWT Certificate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>B2C_Customer_ID__c</fullName>
    <description>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</description>
    <inlineHelpText>... represents the internal B2C Commerce customer profile identifier associated to a given contact.</inlineHelpText>
    <label>B2C Customer ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/Contact/fields/B2C_CustomerList__c.field-meta.xml
<CustomField>
    <fullName>B2C_CustomerList__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>... represents the B2C Commerce CustomerList the customer profile is associated to.</description>
    <inlineHelpText>... represents the B2C Commerce CustomerList the customer profile is associated to.</inlineHelpText>
    <label>B2C CustomerList</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/Contact/fields/B2C_Instance__c.field-meta.xml
<CustomField>
    <fullName>B2C_Instance__c</fullName>
    <description>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</description>
    <formula>B2C_CustomerList__r.B2C_Instance__r.Name</formula>
    <inlineHelpText>... represents the parent B2C Instance for the CustomerList record related to a given Contact.</inlineHelpText>
    <label>B2C Instance</label>
    <type>Text</type>
</CustomField>

src/sfdc/extras/sf-connect/base/main/default/classes/B2CDataSourceAddressBookConnection_Test.cls
@IsTest
public with sharing class B2CDataSourceAddressBookConnection_Test {
    @IsTest
    static void prepareData() {

        B2C_Instance__c instance = (B2C_Instance__c)TestDataFactory.createSObject('B2C_Instance__c', new Map<String,Object>{
            'Name' => 'RefArch',
            'API_Url__c' => 'https://test.com'
        });

        B2C_Client_ID__c clientId = (B2C_Client_ID__c)TestDataFactory.createSObject('B2C_Client_ID__c', new Map<String,Object>{
            'Name' => 'my-test-clientId',
            'B2C_Client_ID_Label__c' => 'My Test ClientID',
            'JWT_Certificate_Name__c' => B2CConstant.CERTTEST_VALIDATE_TESTCERTIFICATENAME,
            'Is_Active__c' => true,
            'Audit_Authentication_API_Interactions__c' => true
        });

        B2C_AuthToken__c authToken = (B2C_AuthToken__c)TestDataFactory.createSObject('B2C_AuthToken__c', new Map<String,Object>{
            'B2C_AuthToken__c' => 'my-test-authtoken',
            'B2C_Client_ID__c' => clientId.Id
        });
        B2C_CustomerList__c customerList = (B2C_CustomerList__c)TestDataFactory.createSObject('B2C_CustomerList__c', new Map<String,Object>{
            'Name' => 'RefArch',
            'B2C_Instance__c' => instance.Id,
            'B2C_Client_ID__c' => clientId.Id,
            'CustomerList_ID__c' => 'RefArch',
            'API_Url__c' => 'https://test.com',
            'OCAPI_Version_No__c' => 'v20_10'
        });

        Contact contact = (Contact)TestDataFactory.createSObject('Contact', new Map<String,Object>{
            'LastName' => 'lastname',
            'B2C_CustomerList__c' => customerList.Id,
            'B2C_Customer_ID__c' => '001'
        });

        // Validate that all of the test-data is created
        System.assert(contact != null, 'Expected a contact to be created');
        System.assert(customerList != null, 'Expected a customerList to be created');
        System.assert(authToken != null, 'Expected an authToken to be created');
        System.assert(clientId != null, 'Expected an clientId to be created');
        System.assert(instance != null, 'Expected an instance to be created');

    }

    @IsTest
    static void testTableSync() {
        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            List<DataSource.Table> tables = connection.sync();
        Test.stopTest();

        System.assertEquals(tables.size(), 1, 'The result should contain one table.');
        System.assertNotEquals(tables[0].columns.size(), 0, 'The table should contains columns.');
    }

    @IsTest
    static void testQuerySingleAddressIsSuccess() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        filter.columnName = 'ExternalId';
        filter.columnValue = '001__my_home_address';
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertNotEquals(result.rows.size(), 0, 'The rows should contain at least one result.');
    }

    @IsTest
    static void testQueryAddressesWithoutFilter() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertEquals(result.rows.size(), 0, 'The rows should not contain any result.');
    }

    @IsTest
    static void testQuerySingleAddressIsFailure() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        filter.columnName = 'ExternalId';
        filter.columnValue = '001__my_home_address';
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressFailure'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertEquals(result.rows.size(), 0, 'The rows should not contain any result.');
    }

    @IsTest
    static void testQueryMultipleAddressesIsSuccess() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        filter.columnName = 'CustomerId';
        filter.columnValue = '001';
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.Filter subFilter = new DataSource.Filter();
        subFilter.columnName = 'CustomerId';
        subFilter.columnValue = '001';
        subFilter.type = DataSource.FilterType.EQUALS;
        filter.subfilters = new List<DataSource.Filter>{ subFilter };
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressesSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertNotEquals(result.rows.size(), 0, 'The rows should contain at least one result.');
    }

    @IsTest
    static void testQueryMultipleAddressesWrongCustomerNo() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        filter.columnName = 'CustomerId';
        filter.columnValue = '';
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.Filter subFilter = new DataSource.Filter();
        subFilter.columnName = 'CustomerId';
        subFilter.columnValue = '';
        subFilter.type = DataSource.FilterType.EQUALS;
        filter.subfilters = new List<DataSource.Filter>{ subFilter };
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressesSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertEquals(result.rows.size(), 0, 'The rows should contain at least one result.');
    }


    @IsTest
    static void testQueryMultipleAddressesContactNotFound() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        String customerId = '002';
        filter.columnName = 'CustomerId';
        filter.columnValue = customerId;
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.Filter subFilter = new DataSource.Filter();
        subFilter.columnName = 'CustomerId';
        subFilter.columnValue = customerId;
        subFilter.type = DataSource.FilterType.EQUALS;
        filter.subfilters = new List<DataSource.Filter>{ subFilter };
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressesSuccess'));

        Test.startTest();
        try{
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        } catch (Exception e) {
            System.assertEquals(
                B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_CONTACTNOTFOUND, customerId),
                e.getMessage(),
                'We should have as much results as rows to update.'
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void testQueryMultipleAddressesIsFailure() {
        // create the QueryContext class
        DataSource.QueryContext context = new DataSource.QueryContext();
        // create the filter class and set the ColumnName
        DataSource.Filter filter = new DataSource.Filter();
        filter.columnName = 'CustomerId';
        filter.columnValue = '001';
        filter.type = DataSource.FilterType.EQUALS;
        DataSource.Filter subFilter = new DataSource.Filter();
        subFilter.columnName = 'CustomerId';
        subFilter.columnValue = '001';
        subFilter.type = DataSource.FilterType.EQUALS;
        filter.subfilters = new List<DataSource.Filter>{ subFilter };
        DataSource.ColumnSelection columnSelection = new DataSource.ColumnSelection();
        columnSelection.columnName = 'ExternalId';
        columnSelection.tableName = 'B2C_CustomerAddress__x';
        // create the TableSelection class, set the filter and add it to the QueryContext
        DataSource.TableSelection tableSelection = new DataSource.TableSelection();
        tableSelection.tableSelected = 'B2C_CustomerAddress__x';
        tableSelection.columnsSelected = new List<DataSource.ColumnSelection>{ columnSelection };
        tableSelection.filter = filter;
        context.tableSelection = tableSelection;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressesFailure'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            DataSource.TableResult result = connection.query(context);
        Test.stopTest();

        System.assertEquals(result.success, true, 'The result should be a success.');
        System.assertEquals(result.tableName, 'B2C_CustomerAddress__x', 'The table name should be the one selected.');
        System.assertEquals(result.rows.size(), 0, 'The rows should not contain any result.');
    }

    @IsTest
    static void testUpsertAddressWrongCustomerNo() {
        // create the UpsertContext class
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        context.tableSelected = 'B2C_CustomerAddress__x';
        List<Map<String, Object>> rows = new List<Map<String, Object>>();
        Map<String, Object> row = new Map<String, Object>();
        row.put('ExternalId', '__my_home_address');
        row.put('city', 'San Francisco');
        rows.add(row);
        context.rows = rows;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressPatchSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            List<DataSource.UpsertResult> result = connection.upsertRows(context);
        Test.stopTest();

        System.assertEquals(rows.size(), result.size(), 'We should have as much results as rows to update.');
        System.assertNotEquals(result[0].success, true, 'The update should be a success.');
    }

    @IsTest
    static void testUpsertAddressContactNotFound() {
        // create the UpsertContext class
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        String customerId = '002';
        context.tableSelected = 'B2C_CustomerAddress__x';
        List<Map<String, Object>> rows = new List<Map<String, Object>>();
        Map<String, Object> row = new Map<String, Object>();
        row.put('ExternalId', customerId + '__my_home_address');
        row.put('city', 'San Francisco');
        rows.add(row);
        context.rows = rows;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressPatchSuccess'));

        Test.startTest();
        try {
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            List<DataSource.UpsertResult> result = connection.upsertRows(context);
        } catch (Exception e) {
            System.assertEquals(
                B2CConstant.buildErrorMessage(B2CConstant.ERRORS_META_CONTACTNOTFOUND, customerId),
                e.getMessage(),
                'We should have as much results as rows to update.'
            );
        }
        Test.stopTest();
    }

    @IsTest
    static void testUpsertAddressIsSuccess() {
        // create the UpsertContext class
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        context.tableSelected = 'B2C_CustomerAddress__x';
        List<Map<String, Object>> rows = new List<Map<String, Object>>();
        Map<String, Object> row = new Map<String, Object>();
        row.put('ExternalId', '001__my_home_address');
        row.put('city', 'San Francisco');
        rows.add(row);
        context.rows = rows;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressPatchSuccess'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            List<DataSource.UpsertResult> result = connection.upsertRows(context);
        Test.stopTest();

        System.assertEquals(rows.size(), result.size(), 'We should have as much results as rows to update.');
        System.assertEquals(result[0].success, true, 'The update should be a success.');
    }

    @IsTest
    static void testUpsertAddressIsFailure() {
        // create the UpsertContext class
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        context.tableSelected = 'B2C_CustomerAddress__x';
        List<Map<String, Object>> rows = new List<Map<String, Object>>();
        Map<String, Object> row = new Map<String, Object>();
        row.put('ExternalId', '001__my_home_address');
        row.put('city', 'San Francisco');
        rows.add(row);
        context.rows = rows;

        prepareData();
        Test.setMock(HttpCalloutMock.class, new B2CHttpTestCalloutMockGenerator('CustomerAddressPatchFailure'));

        Test.startTest();
            DataSource.ConnectionParams connectionParams = new DataSource.ConnectionParams();
            B2CDataSourceAddressBookProvider provider = new B2CDataSourceAddressBookProvider();
            DataSource.Connection connection = provider.getConnection(connectionParams);
            List<DataSource.UpsertResult> result = connection.upsertRows(context);
        Test.stopTest();

        System.assertEquals(rows.size(), result.size(), 'We should have as much results as rows to update.');
        System.assertNotEquals(result[0].success, true, 'The update should be a failure.');
    }
}