src/sfdc/force-app/main/default/objects/B2C_Site__c/B2C_Site__c.object-meta.xml
<CustomObject>
    <description>... custom object used to represent B2C Commerce storefronts.</description>
    <label>B2C Site</label>
    <nameField>
        <label>B2C Site ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2C Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/API_Url__c.field-meta.xml
<CustomField>
    <fullName>API_Url__c</fullName>
    <description>... represents the API url used to retrieve B2C Commerce storefront details.</description>
    <inlineHelpText>... represents the API url used to retrieve B2C Commerce storefront details.</inlineHelpText>
    <label>Record API Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Base_Custom_Site_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_Custom_Site_Url__c</fullName>
    <description>... represents the custom external / customer-facing url used to access a storefront.</description>
    <inlineHelpText>... represents the custom external / customer-facing url used to access a storefront.</inlineHelpText>
    <label>Base Custom Site Url</label>
    <type>Url</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Base_Internal_Site_Url__c.field-meta.xml
<CustomField>
    <fullName>Base_Internal_Site_Url__c</fullName>
    <description>... represents the base internal url used to access the B2C Commerce storefront environment.</description>
    <formula>LEFT(API_Url__c, FIND( &apos;/s/&apos;, API_Url__c)-1) &amp; &quot;/on/demandware.store/Sites-&quot; &amp;  Name &amp; &quot;-Site&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>... represents the base internal url used to access the B2C Commerce storefront environment.</inlineHelpText>
    <label>Base Internal Site Url</label>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Customer_List__c.field-meta.xml
<CustomField>
    <fullName>Customer_List__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>... represents the B2C Commerce parent CustomerList.</description>
    <inlineHelpText>... represents the B2C Commerce parent CustomerList.</inlineHelpText>
    <label>Customer List</label>
    <referenceTo>B2C_CustomerList__c</referenceTo>
    <relationshipLabel>B2C Sites</relationshipLabel>
    <relationshipName>B2C_Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/CustomerList_ID__c.field-meta.xml
<CustomField>
    <fullName>CustomerList_ID__c</fullName>
    <description>... represents the B2C Commerce customer-facing identifier for a given CustomerList.</description>
    <externalId>true</externalId>
    <inlineHelpText>... represents the B2C Commerce customer-facing identifier for a given CustomerList.</inlineHelpText>
    <label>CustomerList ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>... describes a given B2C Commerce Storefront.</description>
    <inlineHelpText>... describes a given B2C Commerce Storefront.</inlineHelpText>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/Enable_Address_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Address_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Address Book addresses can be created for this Site as Salesforce Platform custom objects.</description>
    <inlineHelpText>... describes whether B2C Commerce Address Book addresses can be created for this Site as Salesforce Platform custom objects.</inlineHelpText>
    <label>Enable Address Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/Enable_Address_Updates__c.field-meta.xml
<CustomField>
    <fullName>Enable_Address_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Address Book addresses can be updated for this Site as Salesforce Platform custom objects.</description>
    <inlineHelpText>... describes whether B2C Commerce Address Book addresses can be updated for this Site as Salesforce Platform custom objects.</inlineHelpText>
    <label>Enable Address Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Enable_Profile_Creation__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes whether B2C Commerce Profiles can be created for this B2C Commerce Storefront.</description>
    <inlineHelpText>... describes whether B2C Commerce Profiles can be created for this B2C Commerce Storefront.</inlineHelpText>
    <label>Enable Profile Creation</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Enable_Profile_Updates__c.field-meta.xml
<CustomField>
    <fullName>Enable_Profile_Updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if B2C Commerce profiles can be updated for this B2C Commerce Storefront.</description>
    <inlineHelpText>... describes if B2C Commerce profiles can be updated for this B2C Commerce Storefront.</inlineHelpText>
    <label>Enable Profile Updates</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>... describes if a given B2C Commerce storefront is active and accepting integration activities.</description>
    <inlineHelpText>... describes if a given B2C Commerce storefront is active and accepting integration activities.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/Named_Credential_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Developer_Name__c</fullName>
    <description>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this site.</description>
    <inlineHelpText>... represents the internal Salesforce Platform Developer Name for the Named Credential that should be used to interact with B2C Commerce OCAPI REST APIs for this site.</inlineHelpText>
    <label>Named Credential Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/OOBO_Active_Url__c.field-meta.xml
<CustomField>
    <fullName>OOBO_Active_Url__c</fullName>
    <description>... represents the url type that is actively being leveraged to invoke the OOBO customer experience.</description>
    <inlineHelpText>... represents the url type that is actively being leveraged to invoke the OOBO customer experience.</inlineHelpText>
    <label>OOBO Active Url</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/force-app/main/default/objects/B2C_Site__c/fields/Storefront_Name__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Name__c</fullName>
    <description>... customer-facing name / label for a given B2C Commerce Storefront.</description>
    <inlineHelpText>... customer-facing name / label for a given B2C Commerce Storefront.</inlineHelpText>
    <label>Storefront Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/sfdc/base/main/default/objects/B2C_Site__c/fields/Storefront_Status__c.field-meta.xml
<CustomField>
    <fullName>Storefront_Status__c</fullName>
    <description>... represents the current online status for a given B2C Commerce Storefront.</description>
    <inlineHelpText>... represents the current online status for a given B2C Commerce Storefront.</inlineHelpText>
    <label>Storefront Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
                <default>true</default>
                <label>Online</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Protected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/sfdc/force-app/main/default/classes/B2CStorefrontManager.cls
/**
 * @author Abraham David Lloyd
 * @date January 20th, 2020
 *
 * @description This class is used to retrieve B2C Commerce storefront data and details
 * from custom object collections.
*/
public with sharing class B2CStorefrontManager extends B2CBaseMeta {

    /**
     * @description Attempts to retrieve a storefront configured via custom objects.  This method
     * automatically throws an error if no records are found and filters on active records.
     *
     * @param siteId {String} Describes the siteId identifier used to retrieve a given definition
     * @return B2C Returns an instance of the customer list
     */
    public static B2C_Site__c getStorefront(String siteId) {
        return getStorefront(siteId, true, false);
    }

    /**
     * @description Attempts to retrieve a storefront configured via custom objects.  This method
     * automatically throws an error if no records are found and filters on active records.
     *
     * @param siteId {String} Describes the siteId identifier used to retrieve a given definition
     * @return B2C Returns an instance of the customer list
     */
    public static B2C_Site__c getStorefrontById(String siteId) {
        return getStorefrontById(siteId, true, false);
    }

    /**
     * @description Attempts to resolve a B2C Commerce storefront for a given siteId
     *
     * @param siteId {String} Describe the siteId used to retrieve a storefront definition
     * @param filterOnActive {Boolean} Describes if the query should filter on active objects only
     * @param returnEmptyObject {Boolean} Describes if an empty sObject should be returned if no results are found
     * @return {B2C_Sites} Returns an instance of the storefront
     */
    public static B2C_Site__c getStorefront(String siteId, Boolean filterOnActive, Boolean returnEmptyObject) {

        // Initialize local variables
        List<B2C_Site__c> storefronts;
        String errorMsg;
        Query siteQuery;
        B2C_Site__c output;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_NoActiveStorefrontFound, siteId);

        // Seed the default query structure to leverage
        siteQuery = getDefaultQuery();

        // Define the record limit for the query
        siteQuery.setLimit(1);

        // Define the default where-clause for the query
        siteQuery.addConditionEq('Name', siteId);

        // Should only active-records be filtered?
        if (filterOnActive == true) {

            // If so, then append the active-flag to the query's where clause
            siteQuery.addConditionEq('Is_Active__c', true);

        }

        // Execute the query and evaluate the results
        storefronts = siteQuery.run();

        // Process the return results in a consistent manner
        output = (B2C_Site__c)processReturnResult('B2C_Site__c', returnEmptyObject, storefronts, errorMsg);

        // Return the site result
        return output;

    }

    /**
     * @description Attempts to resolve a B2C Commerce storefront for a given siteId
     *
     * @param crmSiteId {String} Describe the siteId used to retrieve a storefront definition
     * @param filterOnActive {Boolean} Describes if the query should filter on active objects only
     * @param returnEmptyObject {Boolean} Describes if an empty sObject should be returned if no results are found
     * @return {B2C_Sites} Returns an instance of the storefront
     */
    public static B2C_Site__c getStorefrontById(String crmSiteId, Boolean filterOnActive, Boolean returnEmptyObject) {

        // Initialize local variables
        List<B2C_Site__c> storefronts;
        String errorMsg;
        Query siteQuery;
        B2C_Site__c output;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_NoActiveStorefrontFound, crmSiteId);

        // Seed the default query structure to leverage
        siteQuery = getDefaultQuery();

        // Define the record limit for the query
        siteQuery.setLimit(1);

        // Define the default where-clause for the query
        siteQuery.addConditionEq('Id', crmSiteId);

        // Should only active-records be filtered?
        if (filterOnActive == true) {

            // If so, then append the active-flag to the query's where clause
            siteQuery.addConditionEq('Is_Active__c', true);

        }

        // Execute the query and evaluate the results
        storefronts = siteQuery.run();

        // Process the return results in a consistent manner
        output = (B2C_Site__c)processReturnResult('B2C_Site__c', returnEmptyObject, storefronts, errorMsg);

        // Return the site result
        return output;

    }

    /**
     * @description Attempts to validate the mapping between a B2C Commerce CustomerList and Storefront
     *
     * @param customerListId {String} Describe the customerList used to retrieve a storefront definition
     * @param siteId {String} Describe the siteId used to retrieve a storefront definition
     * @return {B2C_Sites} Returns an instance of the storefront
     */
    public static B2C_Site__c getStorefrontByCustomerListIdSiteId(String customerListId, String siteId) {

        // Initialize local variables
        List<B2C_Site__c> storefronts;
        String errorMsg;
        Query siteQuery;
        B2C_Site__c output;

        // Default the error message
        errorMsg = B2CConstant.buildErrorMessage(B2CConstant.Errors_Meta_NoActiveStorefrontFound, siteId);

        // Seed the default query structure to leverage
        siteQuery = getDefaultQuery();

        // Define the record limit for the query
        siteQuery.setLimit(1);

        // Define the default where-clause for the query
        siteQuery.addConditionEq('Name', siteId);
        siteQuery.addConditionEq('CustomerList_ID__c', customerListId);
        siteQuery.addConditionEq('Is_Active__c', true);

        // Execute the query and evaluate the results
        storefronts = siteQuery.run();

        // Process the return results in a consistent manner
        output = (B2C_Site__c)processReturnResult('B2C_Site__c', true, storefronts, errorMsg);

        // Return the site result
        return output;

    }

    /**
     * @description Helper method that provides a consistent set of columns to leverage
     * when selecting sObject data via SOQL
     *
     * @return {Query} Returns the query template to leverage for sites
     */
    private static Query getDefaultQuery() {

        // Initialize local variables
        Query siteQuery;

        // Create the profile query that will be used to drive resolution
        siteQuery = new Query('B2C_Site__c');

        // Add the fields to retrieve
        siteQuery.selectField('Id');
        siteQuery.selectField('Name');
        siteQuery.selectField('Customer_List__c');
        siteQuery.selectField('CustomerList_ID__c');
        siteQuery.selectField('Storefront_Name__c');
        siteQuery.selectField('Storefront_Status__c');
        siteQuery.selectField('Base_Custom_Site_Url__c');
        siteQuery.selectField('Base_Internal_Site_Url__c');
        siteQuery.selectField('OOBO_Active_Url__c');
        siteQuery.selectField('API_Url__c');
        siteQuery.selectField('Named_Credential_Developer_Name__c');
        //siteQuery.selectField('Audit_OCAPI_API_Response__c');
        siteQuery.selectField('Is_Active__c');
        siteQuery.selectField('Description__c');
        siteQuery.selectField('Enable_Profile_Creation__c');
        siteQuery.selectField('Enable_Profile_Updates__c');
        siteQuery.selectField('Enable_Address_Creation__c');
        siteQuery.selectField('Enable_Address_Updates__c');

        // Return the default query structure
        return siteQuery;

    }

}